### ISSUE TITLE
Improve (Soroban) transaction submission error reporting (Version: master)

### ISSUE THREAD

**Issue by 2opremio** [stellar/stellar-core#3816] opened 2023-07-06 16:27 UTC
For Soroban devs (and platform developers) it would really really help if transaction submission error messages from Core where more helpful.

In particular they should be **actionable**. For example I have been getting a function-trapped error code for a wide range of problems (ranging from bad auth, to wrong resources). 

If an auth entry is missing, the error should point it out (ideally including what auth should had been included)

If a footprint entry is missing, the error should point it out (ideally indicating what entry should be included) 

If a resource is too low, it should say so, indicating which one is too low

Same when the provided fee is not enough (it should ideally indicate why fee should be used or what is surpasing the provided fee) etc etc etc ...

Note that subpar error reporting was fine (or at least tolerable) in Stellar classic, because the scope of operations was very limited and well defined and the things which could go wrong were also limited. With contracts, an error code is not enough. In fact, soroban error codes are not specific enough or have been misleading (see the `function-trapped` example above).

If you think diagnostic events are the answer, then they should at least be enabled by default.

**Comment by MonsieurNicolas** [comment] 2023-07-07 23:55
Yes you are right: the complexity of Soroban means that we can't just use "error codes" to convey proper feedback to developers (and we want to make those errors richer over time without having to take a dependency on "protocol versions" for that).

`ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` is the config setting that you're looking for, I agree that this setting should probably be "on by default" in the context of the captive-core instance used by Soroban-rpc (but off everywhere else, like validators and Horizon captive-core).

Once enabled, we should be able over time to add more diagnostic events in the host code that help with usability (so open issues [there](https://github.com/stellar/rs-soroban-env/issues)).

I opened https://github.com/stellar/stellar-core/issues/3821 as I noticed this was not documented anywhere.

That being said, you mentioned "transaction submission", and from the looks of it, right now there is no good way to return a great error message from the `tx` endpoint. As you mentioned "traps", this should occur at execution time so we're probably fine for now.

**Comment by graydon** [comment] 2023-07-25 18:41
For context, there are 3 layers of error reporting coming out of core relevant to soroban:

1. The transaction-level error [`InvokeHostFunctionResultCode`](https://github.com/stellar/stellar-xdr/blob/next/Stellar-transaction.x#L1787-L1797), such as `INVOKE_HOST_FUNCTION_TRAPPED`. This is a very coarse-grained error you'll get _in_ the canonical transaction-result record (hashed into history) and the only variant that carries much information at all is `INVOKE_HOST_FUNCTION_SUCCESS`, which carries a hash of the return values and contract events. On error, nothing informative is emitted at this level, because we do not want to be bound to forever reproduce identical precise failure codes in a historical recording of the results.
2. The Soroban `ScError`-level error code. These are _slightly_ more fine-grained codes -- [taken from a small set of type-and-code integer pairs](https://github.com/stellar/stellar-xdr/blob/next/Stellar-contract.x#L90-L118) -- designed both for in-band signalling and handling of errors _inside_ and _between_ contracts and between host and contracts (including contract-generated error codes) as well as _accompanying_ and _summarizing_ diagnostic events. These are _not_ presently surfaced at the transaction-result level.
3. Diagnostic events. These are emitted in the TxMeta stream when doing transaction processing, and for those that represent errors they should usually include (a) an `ScError` code (b) an `ScString` carrying a more-detailed english-language message describing the failure (c) when possible, auxiliary values related to the error (eg. the number, hash, authenticator or whatever that caused the failure).

A few things to note:

  - Diagnostic events are only emitted during transaction processing, not submission. Submitted txs flow through the system and are batched and executed later, on the next ledger close. We do not know what a tx will do when it's submitted -- certainly not what auth actions it will attempt, or which IO it will attempt -- so we're not in a position to report anything much at the point of submission. Only very basic well-formed-request sorts of analysis is done on submission.
  - Diagnostic events are only emitted in the TxMeta stream, not the canonical TransactionResult stream, and are only emitted if the stellar-core node or other soroban host is configured to have them enabled.
  - If a contract author needs more context for an error occurrence, the recommended approach is to compile the contract natively and trap on error -- this will give a precise native stack trace, served by native debuginfo. It will also (by default) capture and print the event log of the contract.

There are two things that might be requested by this bug that we have not yet invested in:
  - Providing source-level debug info in WASM contracts, such that a non-native, on-chain WASM contract failure could provide a stacktrace in terms of the Rust code of the contract. This would make contracts extremely large, incur significant and highly variable runtime costs on failures, be very hard to integrate with the multi-VM-calling system we have, take a ton of engineering effort, and generally work against a lot of goals we have with the system -- we're just not intending to ever support it.
  - Providing some other sort of method of structured diagnostic-context creation, population and propagation such that a failure could convey richer, user-actionable information. This is much more plausible, though I believe the ultimate _communication_ channel for conveying that information would still most likely be in the form of diagnostic events emitted into the TxMeta stream. For example, one thing we currently do is emit contract-function enter/leave events -- a consumer of diagnostic events can then construct a contract-function context for an error by enumerating the entered-and-not-yet-left contract functions. We could similarly emit events for establishing other context (perhaps the authentication context) that would help a user act on an error.

Our (core team's) hope is that by enriching any under-informative error contexts case-by-case with more diagnostic events, the user experience may be made acceptable. Please let us know if this does general plan seems insufficient, and what you'd prefer.

**Comment by MonsieurNicolas** [comment] 2023-07-26 00:54
Also, @2opremio please link to the Soroban-RPC issue that tracks switching the default behavior in that context (note: we should *not* enable diagnostic events in the context of Horizon)

**Comment by 2opremio** [comment] 2023-07-26 16:50
@MonsieurNicolas I've created https://github.com/stellar/soroban-tools/issues/806

**Comment by MonsieurNicolas** [comment] 2023-08-22 00:09
I think we should close this issue for now? wdyt @anupsdf ?

**Comment by anupsdf** [comment] 2023-08-22 02:57
Yes, we can close this issue.

**Closed by anupsdf** 2023-08-22 02:57 UTC
Labels: enhancement

**Comment by 2opremio** [comment] 2023-08-22 07:29
I guess that what @graydon suggested _Providing source-level debug info in WASM contracts_ and _Providing some other sort of method of structured diagnostic-context creation_ haven't been implemented yet?

Are there tickets tracking that?
