### ISSUE TITLE
Catching up to ledger 1326847 (Version: 14.1.1-39)

### ISSUE THREAD

**Issue by bert2002** [stellar/stellar-core#2766] opened 2020-10-21 01:40 UTC
## Issue Description

stellar-core cannot catch up with ledger 1326847.

## Steps to Reproduce
```
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.559 GDAHU [History INFO] Verifying ledgers [1322394,1326848)
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.560 GDAHU [History ERROR] Catchup material failed verification - unsupported ledger version, propagating failure [VerifyLedgerChainWork.cpp:438]
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.560 GDAHU [History ERROR] Upgrade this stellar-core installation to newest version [VerifyLedgerChainWork.cpp:441]
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.560 GDAHU [History INFO] Verifying ledgers [1322394,1326848)
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.560 GDAHU [History INFO] Catching up to ledger 1326847: Failed: verify-ledger-chain
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.560 GDAHU [History INFO] Catching up to ledger 1326847: Succeeded: batch-download-ledger-00142dbf-00143f3f : 280/280 children completed
Oct 21 01:32:41 stellar-1 stellar-core[20123]: 2020-10-21T01:32:41.865 GDAHU [Overlay INFO] Connected to 35.202.159.46:11625
Oct 21 01:32:42 stellar-1 stellar-core[20123]: 2020-10-21T01:32:42.056 GDAHU [Overlay INFO] Peer 35.202.159.46:11625 dropped us; reason: ERR_LOAD (peer rejected)
Oct 21 01:32:43 stellar-1 stellar-core[20123]: 2020-10-21T01:32:43.018 GDAHU [Herder INFO] Quorum information for 1326873 : {"agree":3,"delayed":0,"disagree":0,"fail_at":2,"hash":"59d361","lag_ms":5,"ledger":1326873,"missing":0,"phase":"EXTERNALIZE"}
Oct 21 01:32:43 stellar-1 stellar-core[20123]: 2020-10-21T01:32:43.020 GDAHU [Ledger INFO] Got consensus: [seq=1326875, prev=ca5249, txs=2, ops=2, sv: [ SIGNED@sdf_testnet_1 txH: ae0dfc, ct: 1603243962, upgrades: [ ] ]]
Oct 21 01:32:43 stellar-1 stellar-core[20123]: 2020-10-21T01:32:43.020 GDAHU [Ledger INFO] Close of ledger 1326875 buffered
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.561 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 17/70 (24%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.717 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 18/70 (25%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.720 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 19/70 (27%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.734 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 20/70 (28%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.738 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 21/70 (30%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.747 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 22/70 (31%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.749 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 23/70 (32%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.765 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 25/70 (35%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.767 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 26/70 (37%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.783 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 27/70 (38%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.789 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 29/70 (41%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.808 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 31/70 (44%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.813 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 33/70 (47%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.875 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 34/70 (48%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.876 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 35/70 (50%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.896 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 36/70 (51%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.907 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 37/70 (52%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.908 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 38/70 (54%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.926 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 40/70 (57%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.939 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 41/70 (58%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.941 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 42/70 (60%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.957 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 43/70 (61%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.959 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 44/70 (62%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.960 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 45/70 (64%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.972 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 46/70 (65%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.984 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 47/70 (67%)
Oct 21 01:32:47 stellar-1 stellar-core[20123]: 2020-10-21T01:32:47.986 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 48/70 (68%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.000 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 49/70 (70%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.029 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 50/70 (71%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.036 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 51/70 (72%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.058 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 52/70 (74%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.062 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 53/70 (75%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.075 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 54/70 (77%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.088 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 55/70 (78%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.094 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 56/70 (80%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.101 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 57/70 (81%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.103 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 58/70 (82%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.118 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 59/70 (84%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.119 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 60/70 (85%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.133 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 61/70 (87%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.134 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 62/70 (88%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.149 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 63/70 (90%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.151 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 64/70 (91%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.164 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 65/70 (92%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.186 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 66/70 (94%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.192 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 67/70 (95%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.217 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 69/70 (98%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.234 GDAHU [History INFO] Catching up to ledger 1326847: downloading ledger files 70/70 (100%)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History INFO] Catching up to ledger 1326847: Succeeded: batch-download-ledger-00142dbf-00143f3f : 350/350 children completed
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History INFO] Verifying ledgers [1322394,1326848)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History ERROR] Catchup material failed verification - unsupported ledger version, propagating failure [VerifyLedgerChainWork.cpp:438]
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History ERROR] Upgrade this stellar-core installation to newest version [VerifyLedgerChainWork.cpp:441]
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History INFO] Verifying ledgers [1322394,1326848)
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History INFO] Catching up to ledger 1326847: Failed: verify-ledger-chain
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.396 GDAHU [History INFO] Catching up to ledger 1326847: Succeeded: batch-download-ledger-00142dbf-00143f3f : 350/350 children completed
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.837 GDAHU [Herder INFO] Quorum information for 1326874 : {"agree":3,"delayed":0,"disagree":0,"fail_at":2,"hash":"59d361","lag_ms":4,"ledger":1326874,"missing":0,"phase":"EXTERNALIZE"}
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.840 GDAHU [Ledger INFO] Got consensus: [seq=1326876, prev=2b0e0a, txs=3, ops=82, sv: [ SIGNED@sdf_testnet_2 txH: fb1ed4, ct: 1603243967, upgrades: [ ] ]]
Oct 21 01:32:48 stellar-1 stellar-core[20123]: 2020-10-21T01:32:48.840 GDAHU [Ledger INFO] Close of ledger 1326876 buffered
Oct 21 01:32:54 stellar-1 stellar-core[20123]: 2020-10-21T01:32:54.035 GDAHU [Herder INFO] Quorum information for 1326875 : {"agree":3,"delayed":0,"disagree":0,"fail_at":2,"hash":"59d361","lag_ms":4,"ledger":1326875,"missing":0,"phase":"EXTERNALIZE"}
Oct 21 01:32:54 stellar-1 stellar-core[20123]: 2020-10-21T01:32:54.037 GDAHU [Ledger INFO] Got consensus: [seq=1326877, prev=dc4931, txs=2, ops=51, sv: [ SIGNED@sdf_testnet_1 txH: 8a5edd, ct: 1603243973, upgrades: [ ] ]]
Oct 21 01:32:54 stellar-1 stellar-core[20123]: 2020-10-21T01:32:54.037 GDAHU [Ledger INFO] Close of ledger 1326877 buffered
```

### stellar-core Version
```
# stellar-core version
stellar-core 14.1.1 (5b2989d334f578b00ac9b5996888257f5922a8a4)
```

### Environment

Installed on Debian 10 with the official apt repository. This is happening on two systems of mine on testnet.

### Update

Now it is doing the same at ledger `1326911`.

**Comment by jun0tpyrc** [comment] 2020-10-21 05:43
reason seems the upgrade , but docker hub image is not out yet
```
After the Stellar testnet upgraded to Protocol 14 on 9/29/20, SDF continued testing, and discovered that two rare, specifically constructed transactions could have caused validators to crash on apply. You can find all the details in this Github pull request. Protocol 14 was not yet live on the public network, and no one submitted either transaction on the testnet, so no validators actually encountered the bug.  As soon as we identified the problem, we got to work on a fix, completed it, and deployed it to the testnet.  As of 10/20/20 at 1900 UTC, the testnet runs on Protocol 15.
```

**Comment by MonsieurNicolas** [comment] 2020-10-21 22:57
duplicate of https://github.com/stellar/docker-stellar-core-horizon/issues/211

**Closed by MonsieurNicolas** 2020-10-21 22:57 UTC
Labels: bug
