### ISSUE TITLE
Restarting catch up data after downloaded enough ledge

### ISSUE THREAD

**Issue by datspider** [stellar/stellar-core#1716] opened 2018-06-20 07:05 UTC
When I set up the sync nodes which connect to a Quorum. This node catching up data from s3 normally, but when ledges are downloaded from s3, it restarts automatically and starts catching up again.
![image](https://user-images.githubusercontent.com/12639939/41642581-ea93156c-7492-11e8-87a4-88c3b8d29e8b.png)
Thank you for your support.

**Comment by MonsieurNicolas** [comment] 2018-06-20 17:46
hey thanks.
Fill the issue template, there is not enough information to tell if this is a bug and/or how you got into this situation

**Comment by datspider** [comment] 2018-06-21 07:56
I checked my log file and got this

> 2018-06-20T19:27:04.551 GCO5G [History INFO] Catching up: verifying checkpoint 55671/55676 (99%)
> 2018-06-20T19:27:04.551 GCO5G [History INFO] Catching up: verifying checkpoint 55672/55676 (99%)
> 2018-06-20T19:27:04.551 GCO5G [History INFO] Catching up: verifying checkpoint 55673/55676 (99%)
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catching up: verifying checkpoint 55674/55676 (99%)
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catching up: verifying checkpoint 55675/55676 (99%)
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catching up: verifying checkpoint 55676/55676 (100%)
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Verifying catchup candidate 3563256 with LedgerManager
> 2018-06-20T19:27:04.552 GCO5G [History INFO] History chain [1,3563256] verified
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catchup downloading history archive state for applying buckets at checkpoint 63 not needed
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catchup downloading transactions for range [63..3563263]
> 2018-06-20T19:27:08.820 GCO5G [Herder INFO] Quorum information for 3571850 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-20T19:27:08.876 GCO5G [Ledger INFO] Got consensus: [seq=3571852, prev=7958f7, tx_count=0, sv: [  txH: 00e029, ct: 1529522827, upgrades: [ ] ]]
> 2018-06-20T19:27:08.876 GCO5G [History INFO] Catching up: downloading transactions files 11/55676 (0%)
> 2018-06-20T19:27:11.196 GCO5G [History INFO] Catching up: downloading transactions files 12/55676 (0%)
> 2018-06-20T19:27:11.236 GCO5G [History INFO] Catching up: downloading transactions files 13/55676 (0%)
> 2018-06-20T19:27:11.731 GCO5G [History INFO] Catching up: downloading transactions files 14/55676 (0%)
> 2018-06-20T19:27:12.182 GCO5G [History INFO] Catching up: downloading transactions files 15/55676 (0%)
> 2018-06-20T19:27:12.505 GCO5G [History INFO] Catching up: downloading transactions files 16/55676 (0%)
> 2018-06-20T19:27:12.610 GCO5G [History INFO] Catching up: downloading transactions files 17/55676 (0%)
> 2018-06-20T19:27:12.612 GCO5G [History INFO] Catching up: downloading transactions files 18/55676 (0%)
> 2018-06-20T19:27:12.648 GCO5G [History INFO] Catching up: downloading transactions files 19/55676 (0%)
> 2018-06-20T19:27:12.957 GCO5G [History INFO] Catching up: downloading transactions files 20/55676 (0%)

This is my stellar-core.cfg content:

HTTP_PORT=11626
PUBLIC_HTTP_PORT=true

HTTP_MAX_CLIENT=128
RUN_STANDALONE=false

COMMANDS=[
 "ll?level=info"
]

NODE_NAMES=[
  "GBXI2YQZ2ZSPOI5BNAAMTUNRDA2SWHPI2UIJOXGN2EBNXSUHIEKYGPLC node6",
  "GDPSYEQ7EEVR5R2BK66BLLJFTOZU75XKVHJKS5JJEILFJ6I4B6LPDTEP node7"
]

# these dir are mounted
LOG_FILE_PATH="/usr/local/arm-core/log/stellar-core.log"
BUCKET_DIR_PATH="/usr/local/arm-core/buckets/buckets"

NETWORK_PASSPHRASE="my network phrase"

PEER_PORT=11625
TARGET_PEER_CONNECTIONS=3
MAX_PEER_CONNECTIONS=10
PREFERRED_PEERS=["ip of node6", "ip of node 7"]
PREFERRED_PEER_KEYS=["$node6", "$node7"]
PREFERRED_PEERS_ONLY=false
NODE_SEED="SDHR4GZWAJZB2JFZTFK4RARJMXURVRTZ73AIENSFGA4RWSWFAERW4DU2"
NODE_IS_VALIDATOR=false

FAILURE_SAFETY=0
UNSAFE_QUORUM=true
CATCHUP_COMPLETE=true

MAX_CONCURRENT_SUBPROCESSES=10

[QUORUM_SET]
VALIDATORS=["$node6", "$node7"]

[HISTORY.local]
get="aws s3 cp s3_address"


I set up this node to connect and get data (connected with 2 nodes of my quorum) and submit transactions also and this node is not validator.

Thank you for your help.

**Comment by MonsieurNicolas** [comment] 2018-06-21 17:53
include what is happening between retries, ie, before "Downloading checkpoints"

**Comment by datspider** [comment] 2018-06-22 02:18
I found the problem, Core is catching ledge but in DB (I used postgres) don't have 'ledge_history' relation, so the data which is cached can't update the ledge history of Core then after catch up it will restart.
Trying to fixing it, thank you for your help.

**Comment by MonsieurNicolas** [comment] 2018-06-22 18:19
This is not a table that core manages or uses. If your stellar-core is properly syncing to the network, we should close this issue.

**Comment by triamnetwork** [comment] 2018-06-25 08:39
I think the problem is here

> 2018-06-20T19:27:04.552 GCO5G [History INFO] Verifying catchup candidate 3563256 with LedgerManager
> 2018-06-20T19:27:04.552 GCO5G [History INFO] History chain [1,3563256] verified
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catchup downloading history archive state for applying buckets at checkpoint 63 not needed
> 2018-06-20T19:27:04.552 GCO5G [History INFO] Catchup downloading transactions for range [63..3563263]

after catching all file your server verified those file(History chain [1,3563256] verified) but  I don't understand what is "Catchup downloading history archive state for applying buckets at checkpoint 63 not needed" mean, and then your server starts to catch up again.

**Comment by datspider** [comment] 2018-06-27 09:34
This is how my nodes set up:
Testnet:
1 full node, 1 sync node, and 1 external node
The full node will Validate the transaction and write this transaction to S3 server.
Sync node will catch up data from S3, connect to the Full node to use this node as "validator".
The external node will catch up data from S3, connect to Sync node and use the Full node as "validator".
My testnet's nodes running normally, all server can catch up and use to receive the transaction and send this to full node.
Mainnet:
2 full node, 5 regular nodes, 1 sync node, and 1 external node
Full node and regular node are validators, they will validate the transaction and Full node will write this transaction to S3 server.
2 Sync node will catch up data from S3, connect to 2 regular nodes to use that node as "validator".
The external node will catch up data from S3, connect to 2 Sync node and use node6 and node 7 as "validator".
Sync nodes and external in my main net after catching up data will reset and catching up again.
![aws network diagram 1](https://user-images.githubusercontent.com/12639939/41965869-e032ab06-7a27-11e8-945c-92671378989f.png)

**Comment by vogel** [comment] 2018-06-27 11:58
Catching has several phases:

1. download ledgers
2. verify ledgers
3. download buckets (can be skipped in some cases, as in yours)
4. apply buckets (can be skipped in some cases, as in yours)
5. download transactions
6. apply transactions

So in your case it is:

1. download ledgers
2. verify ledgers
5. download transactions
6. apply transactions

I think you are mistaking start of phase 5 with restart of phase 1. I am right?

**Comment by triamnetwork** [comment] 2018-06-28 01:22
Yes, I think you are right. 
The log from stellar core don't show downloading buckets but docker log has it.
When I checking my test net server, the sync node "restart catching up" one time and "apply buckets" (I remember it's logged as "replacing buffering ledge" maybe) but in my main net it's can't do it.
stellar_core.cfg is the same in two systems.

**Comment by datspider** [comment] 2018-06-28 01:52
I got this log when checking docker's log
> 2018-06-28T01:50:35.191 GCUJR [History INFO] Catching up: downloading transactions files 15355/57656 (26%)
> 2018-06-28T01:50:35.223 GCUJR [History INFO] Catching up: downloading transactions files 15356/57656 (26%)
> 2018-06-28T01:50:35.260 GCUJR [History INFO] Catching up: downloading transactions files 15357/57656 (26%)
> 2018-06-28T01:50:35.291 GCUJR [History INFO] Catching up: downloading transactions files 15358/57656 (26%)
> download: s3://pro-arm-2/clusters/core-history/cluster-001/transactions/00/0e/fd/transactions-000efd3f.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efd3f.xdr.gz.tmp
> 2018-06-28T01:50:35.495 GCUJR [History INFO] Catching up: downloading transactions files 15359/57656 (26%)
> download: s3://pro-arm-2/clusters/core-history/cluster-001/transactions/00/0e/fc/transactions-000efcff.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efcff.xdr.gz.tmp
> download: s3://pro-arm-2/clusters/core-history/cluster-001/transactions/00/0e/fd/transactions-000efd7f.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efd7f.xdr.gz.tmp

**Comment by datspider** [comment] 2018-06-28 01:53
I got this log when checking docker's log

> 2018-06-28T01:50:35.191 GCUJR [History INFO] Catching up: downloading transactions files 15355/57656 (26%)
> 2018-06-28T01:50:35.223 GCUJR [History INFO] Catching up: downloading transactions files 15356/57656 (26%)
> 2018-06-28T01:50:35.260 GCUJR [History INFO] Catching up: downloading transactions files 15357/57656 (26%)
> 2018-06-28T01:50:35.291 GCUJR [History INFO] Catching up: downloading transactions files 15358/57656 (26%)
> download: s3://my-domain/clusters/core-history/cluster-001/transactions/00/0e/fd/transactions-000efd3f.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efd3f.xdr.gz.tmp
> 2018-06-28T01:50:35.495 GCUJR [History INFO] Catching up: downloading transactions files 15359/57656 (26%)
> download: s3://my-domain/clusters/core-history/cluster-001/transactions/00/0e/fc/transactions-000efcff.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efcff.xdr.gz.tmp
> download: s3://my-domain/clusters/core-history/cluster-001/transactions/00/0e/fd/transactions-000efd7f.xdr.gz to ../arm-core/buckets/buckets/tmp/catchup-098e7b840b731106/transactions-000efd7f.xdr.gz.tmp

**Comment by datspider** [comment] 2018-06-28 08:08
I find the problem in log

> 2018-06-28T07:56:03.072 GCUJR [History INFO] Catchup downloading history archive state for applying buckets at checkpoint 63 not needed
> 2018-06-28T07:56:03.072 GCUJR [History INFO] Catchup applying transactions for range [1..3689962]
> 2018-06-28T07:56:03.072 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:03.073 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:03.074 GCUJR [Work WARNING] Scheduling retry #1/5 in 2 sec, for apply-ledger-chain
> 2018-06-28T07:56:04.571 GCUJR [Herder INFO] Quorum information for 3701797 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:04.573 GCUJR [Ledger INFO] Got consensus: [seq=3701799, prev=52237c, tx_count=0, sv: [  txH: ffb1bc, ct: 1530172564, upgrades: [ ] ]]
> 2018-06-28T07:56:04.573 GCUJR [History INFO] Catching up: Retrying in 1 sec: apply-ledger-chain
> 2018-06-28T07:56:05.074 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:05.074 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:05.074 GCUJR [Work WARNING] Scheduling retry #2/5 in 3 sec, for apply-ledger-chain
> 2018-06-28T07:56:08.075 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:08.075 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:08.075 GCUJR [Work WARNING] Scheduling retry #3/5 in 1 sec, for apply-ledger-chain
> 2018-06-28T07:56:09.075 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:09.075 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:09.075 GCUJR [Work WARNING] Scheduling retry #4/5 in 7 sec, for apply-ledger-chain
> 2018-06-28T07:56:09.582 GCUJR [Herder INFO] Quorum information for 3701798 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:09.584 GCUJR [Ledger INFO] Got consensus: [seq=3701800, prev=3cf14d, tx_count=0, sv: [  txH: 0c44d6, ct: 1530172569, upgrades: [ ] ]]
> 2018-06-28T07:56:09.584 GCUJR [History INFO] Catching up: Retrying in 7 sec: apply-ledger-chain
> 2018-06-28T07:56:14.542 GCUJR [Herder INFO] Quorum information for 3701799 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:14.547 GCUJR [Ledger INFO] Got consensus: [seq=3701801, prev=36b19c, tx_count=0, sv: [  txH: f57bfa, ct: 1530172573, upgrades: [ ] ]]
> 2018-06-28T07:56:14.547 GCUJR [History INFO] Catching up: Retrying in 2 sec: apply-ledger-chain
> 2018-06-28T07:56:16.075 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:16.075 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:16.075 GCUJR [Work WARNING] Scheduling retry #5/5 in 19 sec, for apply-ledger-chain
> 2018-06-28T07:56:19.556 GCUJR [Herder INFO] Quorum information for 3701800 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:19.559 GCUJR [Ledger INFO] Got consensus: [seq=3701802, prev=c912bd, tx_count=0, sv: [  txH: b33a3a, ct: 1530172579, upgrades: [ ] ]]
> 2018-06-28T07:56:19.559 GCUJR [History INFO] Catching up: Retrying in 16 sec: apply-ledger-chain
> 2018-06-28T07:56:24.561 GCUJR [Herder INFO] Quorum information for 3701801 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:24.564 GCUJR [Ledger INFO] Got consensus: [seq=3701803, prev=c6ff26, tx_count=0, sv: [  txH: 7f0f2e, ct: 1530172584, upgrades: [ ] ]]
> 2018-06-28T07:56:24.564 GCUJR [History INFO] Catching up: Retrying in 11 sec: apply-ledger-chain
> 2018-06-28T07:56:29.552 GCUJR [Herder INFO] Quorum information for 3701802 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:29.554 GCUJR [Ledger INFO] Got consensus: [seq=3701804, prev=61b125, tx_count=0, sv: [  txH: 4939d9, ct: 1530172589, upgrades: [ ] ]]
> 2018-06-28T07:56:29.554 GCUJR [History INFO] Catching up: Retrying in 6 sec: apply-ledger-chain
> 2018-06-28T07:56:34.534 GCUJR [Herder INFO] Quorum information for 3701803 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:34.536 GCUJR [Ledger INFO] Got consensus: [seq=3701805, prev=c33464, tx_count=0, sv: [  txH: 560f5b, ct: 1530172593, upgrades: [ ] ]]
> 2018-06-28T07:56:34.536 GCUJR [History INFO] Catching up: Retrying in 1 sec: apply-ledger-chain
> 2018-06-28T07:56:35.076 GCUJR [History INFO] Replaying contents of 57656 transaction-history files from LCL [seq=1, hash=dc2832]
> 2018-06-28T07:56:35.076 GCUJR [History ERROR] Replay failed: replay of [seq=1, hash=8b1aa3] at LCL [seq=1, hash=dc2832] disagreed on hash [ApplyLedgerChainWork.cpp:269]
> 2018-06-28T07:56:35.076 GCUJR [Work WARNING] Reached retry limit 5 for apply-ledger-chain
> 2018-06-28T07:56:35.076 GCUJR [Work WARNING] Reached retry limit 0 for catchup
> 2018-06-28T07:56:35.076 GCUJR [Ledger ERROR] Error catching up: Connection timed out [LedgerManagerImpl.cpp:533]
> 2018-06-28T07:56:35.076 GCUJR [Ledger ERROR] Catchup will restart at next close. [LedgerManagerImpl.cpp:534]
> 2018-06-28T07:56:35.080 GCUJR [Ledger INFO] Changing state LM_CATCHING_UP_STATE -> LM_BOOTING_STATE
> 2018-06-28T07:56:35.084 GCUJR [Work WARNING] WorkManager got FAILURE_RAISE from catchup
> 2018-06-28T07:56:39.539 GCUJR [Herder INFO] Quorum information for 3701804 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:39.541 GCUJR [Ledger INFO] Got consensus: [seq=3701806, prev=0ae1b5, tx_count=0, sv: [  txH: 7bb1ac, ct: 1530172599, upgrades: [ ] ]]
> 2018-06-28T07:56:39.541 GCUJR [Ledger INFO] Lost sync, local LCL is 1, network closed ledger 3701806
> 2018-06-28T07:56:39.541 GCUJR [Ledger INFO] Close of ledger 3701806 buffered, starting catchup
> 2018-06-28T07:56:39.541 GCUJR [Ledger INFO] Changing state LM_BOOTING_STATE -> LM_CATCHING_UP_STATE
> 2018-06-28T07:56:39.542 GCUJR [History INFO] Starting catchup with configuration:
>   lastClosedLedger: 1
>   toLedger: 3701805
>   count: 4294967295
> 2018-06-28T07:56:39.542 GCUJR [History INFO] Catchup downloading history archive state at checkpoint 3701823
> 2018-06-28T07:56:39.543 GCUJR [Work WARNING] Scheduling retry #1/5 in 36 sec, for get-history-archive-state
> 2018-06-28T07:56:44.534 GCUJR [Herder INFO] Quorum information for 3701805 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:44.537 GCUJR [Ledger INFO] Got consensus: [seq=3701807, prev=98360e, tx_count=0, sv: [  txH: fee79c, ct: 1530172604, upgrades: [ ] ]]
> 2018-06-28T07:56:44.537 GCUJR [History INFO] Catching up: Awaiting checkpoint (ETA: 31 seconds)
> 2018-06-28T07:56:49.583 GCUJR [Herder INFO] Quorum information for 3701806 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}
> 
> 2018-06-28T07:56:49.585 GCUJR [Ledger INFO] Got consensus: [seq=3701808, prev=e8688a, tx_count=0, sv: [  txH: 01930b, ct: 1530172609, upgrades: [ ] ]]
> 2018-06-28T07:56:49.586 GCUJR [History INFO] Catching up: Awaiting checkpoint (ETA: 26 seconds)
> 2018-06-28T07:56:54.533 GCUJR [Herder INFO] Quorum information for 3701807 : {"agree":2,"disagree":0,"fail_at":1,"hash":"f3ced8","missing":0,"phase":"EXTERNALIZE"}

The hash is incorrect maybe but I don't understand why it happened. My main server can not replay content of transaction-history.
After this, the server restart and start to catch up "ledge files" not "transactions files"

**Comment by datspider** [comment] 2018-06-28 08:21
When checking TEST NET I got this log after catch up "transactions file"

> 2018-06-28T08:20:14.541 GAFUC [History INFO] Catching up: applying checkpoint 1028/17551 (5%)
> 2018-06-28T08:20:14.701 GAFUC [History INFO] Catching up: applying checkpoint 1029/17551 (5%)
> 2018-06-28T08:20:14.860 GAFUC [History INFO] Catching up: applying checkpoint 1030/17551 (5%)
> 2018-06-28T08:20:15.023 GAFUC [History INFO] Catching up: applying checkpoint 1031/17551 (5%)
> 2018-06-28T08:20:15.182 GAFUC [History INFO] Catching up: applying checkpoint 1032/17551 (5%)
> 2018-06-28T08:20:15.344 GAFUC [History INFO] Catching up: applying checkpoint 1033/17551 (5%)
> 2018-06-28T08:20:15.505 GAFUC [History INFO] Catching up: applying checkpoint 1034/17551 (5%)
My MAIN NET can't applying checkpoint.

**Comment by vogel** [comment] 2018-06-28 12:30
You are probably mixing network_passphase from pubnet with history archives from testnet or vice versa. Please check your configuration and do a --newdb if neccessary.

**Comment by datspider** [comment] 2018-06-29 01:39
I recognize the problems, in the past, my system has 4 nodes, when I want to upgrade it to 7 nodes, I copy buckets of 4 old nodes to 7 new nodes then run force scp for this 7 nodes. I checked the postgres and in my DB, the ledgeheader start from 3xxxxx not 1, but the data in S3 is full from the system start. So when applying the first transaction/ledge file It will disagree it, I am right?
Do you have any suggestion on this situation? How can I fix it without restart or clear DB of my 7 new nodes
I got XDR extension file on S3 and convert it to base64 file but how can I read it? Stellar laboratory seems not for it.
Thank you for your support.

**Comment by MonsieurNicolas** [comment] 2018-12-06 22:32
I am closing this as it seems it's not an actual issue but a conversation at this point.
Maybe @vogel can follow up on that question if it's still relevant

**Closed by MonsieurNicolas** 2018-12-06 22:32 UTC
