### ISSUE TITLE
The size of database is increasing rapidly

### ISSUE THREAD

**Issue by haruki515** [stellar/stellar-core#2219] opened 2019-08-08 11:33 UTC
Hi Stellar developers,

I have a server with 150 GB instance on AWS,  and disk increase 6GB  per day.

I thought 120GB disk is enough to running stellar node.

https://www.stellar.org/developers/guides/hardware.html
https://www.stellar.org/developers/stellar-core/software/admin.html

Is this a normal phenomenon?

## Expected Result
Disk size is enough as written in the requirements.

## Actual Result
120 GB is not enough to running stellar core.

## Environment
[stellar/quickstart](https://hub.docker.com/r/stellar/quickstart/)
```
"info" : {
      "build" : "v11.1.0",
      "history_failure_rate" : "0",
      "ledger" : {
         "age" : 9,
         "baseFee" : 100,
         "baseReserve" : 5000000,
         "closeTime" : 1565263645,
         "hash" : "bab2e0b082b194a87e6e5cf43dc9eb66def05250e9b15b6036a97e41f3f38076",
         "maxTxSetSize" : 1000,
         "num" : 25227681,
         "version" : 11
      }
```

Environment
Amazon linux
t3.large

This is my instance volume.

```
# du -sh /data/*
1.7G    /data/core
24K     /data/horizon
16K     /data/lost+found
63G     /data/postgresql
12K     /data/supervisor
```

```
# du -sh /data/postgresql/data/base/*
6.9M    /data/postgresql/data/base/1
6.9M    /data/postgresql/data/base/12404
7.0M    /data/postgresql/data/base/12405
60G     /data/postgresql/data/base/16384
2.5G    /data/postgresql/data/base/16385
```

**Comment by haruki515** [comment] 2019-08-08 11:38
```
# cat /data/core/etc/stellar-core.cfg
HTTP_PORT=11626
PUBLIC_HTTP_PORT=true
LOG_FILE_PATH="/log"

DATABASE="postgresql://dbname=core host=localhost user=user password=password"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
CATCHUP_RECENT=8640


NODE_NAMES=[
"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U  eno",
"GAXP5DW4CVCW2BJNPFGTWCEGZTJKTNWFQQBE5SCWNJIJ54BOHR3WQC3W  moni",
"GBFZFQRGOPQC5OEAWO76NOY6LBRLUNH4I5QYPUYAK53QSQWVTQ2D4FT5  dzham",
"GDXWQCSKVYAJSUGR2HBYVFVR7NA7YWYSYK3XYKKFO553OQGOHAUP2PX2  jianing",
"GCJCSMSPIWKKPR7WEPIQG63PDF7JGGEENRC33OKVBSPUDIRL6ZZ5M7OO  tempo.eu.com",
"GCCW4H2DKAC7YYW62H3ZBDRRE5KXRLYLI4T5QOSO6EAMUOE37ICSKKRJ  sparrow_tw",
"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3  fuxi.lab",
"GBGGNBZVYNMVLCWNQRO7ASU6XX2MRPITAGLASRWOWLB4ZIIPHMGNMC4I  huang.lab",
"GDPJ4DPPFEIP2YTSQNOKT7NMLPKU2FFVOEIJMG36RCMBWBUR4GTXLL57  nezha.lab",
"GCDLFPQ76D6YUSCUECLKI3AFEVXFWVRY2RZH2YQNYII35FDECWUGV24T  SnT.Lux",
"GBAR4OY6T6M4P344IF5II5DNWHVUJU7OLQPSMG2FWVJAFF642BX5E3GB  telindus",
# non validating
"GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH  sdf_watcher1",
"GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK  sdf_watcher2",
"GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ  sdf_watcher3",
# seem down
"GB6REF5GOGGSEHZ3L2YK6K4T4KX3YDMWHDCPMV7MZJDLHBDNZXEPRBGM  donovan",
"GBGR22MRCIVW2UZHFXMY5UIBJGPYABPQXQ5GGMNCSUM2KHE3N6CNH6G5  nelisky1",
"GA2DE5AQF32LU5OZ5OKAFGPA2DLW4H6JHPGYJUVTNS3W7N2YZCTQFFV6  nelisky2",
"GDJ73EX25GGUVMUBCK6DPSTJLYP3IC7I3H2URLXJQ5YP56BW756OUHIG  w00kie",
"GAM7A32QZF5PJASRSGVFPAB36WWTHCBHO5CHG3WUFTUQPT7NZX3ONJU4  ptarasov"
]

KNOWN_PEERS=[
"core-live-a.stellar.org:11625",
"core-live-b.stellar.org:11625",
"core-live-c.stellar.org:11625",
"confucius.strllar.org",
"stellar1.bitventure.co",
"stellar.256kw.com"]

[QUORUM_SET]
VALIDATORS=[
"$sdf_watcher1","$eno","$tempo.eu.com","$sdf_watcher2","$sdf_watcher3"
]

[HISTORY.cache]
get="cp /opt/stellar/history-cache/{0} {1}"

# Stellar.org history store
[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"
```

**Comment by MonsieurNicolas** [comment] 2019-08-08 20:58
Are you running Horizon? It sounds you are. What is the value of cursors on your system?

You can retrieve them by running something like
```
./stellar-core --conf /my-config.cfg http-command getcursor
```

If cursors are set but not changing it may indicate that Horizon is not ingesting data properly, causing a buildup of old transactions in stellar-core's database.

If this is the problem, what we can do is make it a little easier for people to diagnose this specific problem in the first place.

**Comment by haruki515** [comment] 2019-08-09 00:43
My cursors value is below

```
# /usr/local/bin/stellar-core http-command getcursor
2019-08-09T00:26:00.412 <startup> [default INFO] Assigning calculated value of 1 to FAILURE_SAFETY
Content-Length: 123
Content-Type: application/json

2019-08-09T00:26:00.416 GC6NA [default INFO] {
   "cursors" : [
      {
         "cursor" : 25236388,
         "id" : "HORIZON                         "
      }
   ]
}
```

So, You said that To fix this I have to add my config file this line ?

```
# KNOWN_CURSORS (list of strings) default is empty
# Set of cursors added at each startup with value '1'.
KNOWN_CURSORS=["HORIZON"]
```

**Comment by MonsieurNicolas** [comment] 2019-08-09 15:56
It looks like the cursor is set properly, so the problem is somewhere else:
can you find out which table is taking space?
Also, what is `SELECT min(ledgerseq),max(ledgerseq) FROM ledgerheaders;` returning for you when you logging into the database?

**Comment by haruki515** [comment] 2019-08-13 02:20
@MonsieurNicolas 

This is the result .
It seems to be history tablse is taking space.

```
core=> SELECT min(ledgerseq),max(ledgerseq) FROM ledgerheaders;
   min    |   max
----------+----------
 25301000 | 25301633
(1 row)

core=> SELECT datname, pg_size_pretty(pg_database_size(datname)) FROM pg_database;
  datname  | pg_size_pretty
-----------+----------------
 postgres  | 6953 kB
 template1 | 6953 kB
 template0 | 6953 kB
 horizon   | 76 GB
 core      | 2516 MB
(5 rows)

horizon=> SELECT relname, reltuples, (relpages / 128) as mbytes, (relpages * 8192.0 / (reltuples + 1e-10)) as average_row_size FROM pg_class ORDER BY mbytes DESC;

                        relname                        |  reltuples  | mbytes | average_row_size
-------------------------------------------------------+-------------+--------+------------------
 history_operations                                    | 4.46016e+07 |  18972 | 446.044850751596
 history_transactions                                  |  6.7364e+06 |  11354 | 1767.37081902179
 history_effects                                       |  5.2913e+07 |  11231 |  222.56736875264
 hist_op_p_id                                          |  7.2201e+07 |   4027 | 58.4978111650802
 hist_e_id                                             |  5.2913e+07 |   3827 | 75.8397644071811
 history_operation_participants                        |  7.2201e+07 |   3593 | 52.1843826802987
 hist_e_by_order                                       |  5.2913e+07 |   1591 | 31.5452373999367
 history_operation_participants_pkey                   |  7.2201e+07 |   1546 |  22.463705915965
 hop_by_hoid                                           |  7.2201e+07 |   1546 |  22.463705915965
 index_history_effects_on_type                         |  5.2913e+07 |   1437 | 28.4833580745809
 hist_tx_p_id                                          | 2.57416e+07 |   1364 | 55.5621163845384
 history_transaction_participants                      | 2.57416e+07 |   1281 | 52.1868654774268
 index_history_operations_on_type                      | 4.46016e+07 |   1210 | 28.4566177153761
 by_account                                            |  6.7364e+06 |   1113 | 173.354556928164
 index_history_operations_on_id                        | 4.46016e+07 |    955 | 22.4640011249817
 index_history_operations_on_transaction_id            | 4.46016e+07 |    954 | 22.4302057575672
 by_hash                                               |  6.7364e+06 |    802 | 124.867037329423
 history_transaction_participants_pkey                 | 2.57416e+07 |    551 | 22.4613623443269
 htp_by_htid                                           | 2.57416e+07 |    550 | 22.4078980644481
 history_ledgers                                       |      315386 |    224 | 745.598599811025
 index_history_transactions_on_id                      |  6.7364e+06 |    144 | 22.4512586986347
 by_ledger                                             |  6.7364e+06 |    144 | 22.4512586986347
 hs_transaction_by_id                                  |  6.7364e+06 |    144 | 22.4512586986347
 trade_effects_by_order_book                           |      719617 |    110 | 160.682807660186
 index_history_accounts_on_address                     |      581503 |     63 |  113.71536174362
 history_accounts                                      |      581503 |     56 | 101.247807835901
 history_trades                                        |      354868 |     50 | 149.819313096701
 index_history_ledgers_on_ledger_hash                  |      315386 |     37 |   124.3660022956
 index_history_ledgers_on_previous_ledger_hash         |      315386 |     37 | 124.288078735264
 htrd_pair_time_lookup                                 |      354868 |     25 | 76.1793117440851
 index_history_accounts_on_id                          |      581503 |     12 | 22.4979475600298
 htrd_pid                                              |      354868 |     10 | 31.6028720538341
 htrd_by_base_offer                                    |      354868 |     10 | 29.8715240596503
 htrd_by_counter_account                               |      354868 |     10 |  29.802270139883
 htrd_by_offer                                         |      354868 |     10 | 32.4800883708872
```

**Comment by MonsieurNicolas** [comment] 2019-08-14 02:31
The core database is only taking 2GB of space which is within spec. I am closing this issue.

I can't comment on Horizon as this is a different system, you should ask on the dev-discussion channel in Keybase.

**Closed by MonsieurNicolas** 2019-08-14 02:31 UTC
Labels: bug
