### ISSUE TITLE
Many Overlay errors printed sending after drop (Version: stellar-core 15.2.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2937] opened 2021-03-01 16:36 UTC
## Issue Description

In Horizon stg cluster with Captive Stellar-Core enabled I noticed a large number of Overlay errors similar to:
```
Trying to send message to 144.76.113.106:11625 after drop
Please report this bug along with this log file if this was not expected
```

It would be OK but it looks like Stellar-Core sometimes prints hundreds of lines like this per second. I'm wondering if it's expected.

### stellar-core Version
stellar-core 15.2.0 (54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d)

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)

Linux [redacted server name] #107-Ubuntu SMP Thu Oct 3 01:51:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Are you running from the command line? From a container?

Captive Stellar-Core

* Did you pass in special parameters when building the app?

No

* Please add any additional relevant configuration related to this bug report.

## Supporting Files

N/A

## Additional context
N/A

**Comment by ire-and-curses** [comment] 2021-03-22 16:04
It's triggering our alerts so would be great to fix: https://stellarfoundation.slack.com/archives/CANJGG94K/p1616417239039400

**Comment by hidenori-shinohara** [comment] 2021-08-02 21:13
With a lot of help from @graydon, I was able to reproduce the error and get some insights.

I used lldb to set a breakpoint at the line that produces the error message and tried to reproduce the error as following:
1. Create a simple config for a pubnet watcher.
1. Set a breakpoint and run Core in lldb.
1. Stop with `Ctrl+C`, wait for 30 seconds, and resumed with `c`.

These 3 steps printed the error message dozens of times, and all of them came from `Floodgate.cpp:L131`.
```
            mApp.postOnMainThread(
                [smsg, weak, log = !broadcasted]() {
                    auto strong = weak.lock();
                    if (strong)
                    {
                        strong->sendMessage(*smsg, log);  <------ L131
                    }
                },
                fmt::format("broadcast to {}", peer.second->toString()));
```
It seems that we get to the error message as following:
1. We get a list of peers using `mApp.getOverlayManager().getAuthenticatedPeers();` and loop through them.
1. We create an event for each peer and enqueue it using `postOnMainThread` as shown above.
1. Before the event is executed, the peer has been `shutdown`ed, which means we try to send a message to a closed peer.

At a first glance, I mistakenly thought that Step 3 can't happen as `shutdown()` removes the peer from the authenticated peer list in the overlay manager. However, this code lets us capture the peer in the lambda expression and enqueue it before `shutdown()` and execute it after `shutdown()`.

When we actually enqueue an event containing `sendMessage`, I imagine it's extremely difficult (or pretty much impossible?) to guarantee the previously queued events wouldn't change the value of `mState` before the execution. Furthermore, having multiple queues makes things even more complicated. It is possible that events added later to another queue might get dequeued and change `mState` before the `sendMessage` event.

Then it seems reasonable to add a check before calling `sendMessage` inside `postOnMainThread`. Instead of `if (strong)` we could do `if (strong && strong->getState() != Peer::CLOSING)`. When I tried it, this indeed fixed the error. It made sense to me since, from what I see, this is the only place where `sendMessage` is enqueued using `postOnMainThread`. (at least directly)

Alternatively, we can "fix" this by removing the error message and adding
```
    if (shouldAbort())      
    {     
        return;          
    }
```  
to the beginning of `sendMessage` just like we do with `recvMessage`. This seems somewhat reasonable as this error message was added in https://github.com/stellar/stellar-core/pull/1558 when it assumed serial execution on a per-peer basis, which is no longer the case. So one might argue that this is no longer an error.

What do you think @MonsieurNicolas @marta-lokhova?

**Comment by MonsieurNicolas** [comment] 2021-08-02 22:02
I guess the question I have is: why only do this in the `broadcast` code path? Looking at other places where we call `sendMessage`, is it possible that we're processing (and responding) to messages off dead connections for the same reason that you outline here?

**Comment by graydon** [comment] 2021-08-03 18:38
Most events posted to the main queue that result in a `Peer::sendMessage` are themselves the result of `Peer::recvMessage`: they're lambdas generated 1:1 from messages just received by the peer, that start with a call to `Peer::recvRawMessage`, and the first thing that does is check `shouldAbort`. So the great majority of cases where we _might_ be starting to dispatch work on a dropped peer are already inhibiting themselves as soon as they wake up.

Broadcast is one of the few (perhaps the only?) places we have 1 unit of work from peer X (or spontaneously from us) causing N units of work for peers Y...Z. It's both multiplicative and cross-peer. So to keep the units of work fine grained and also switch to per-receiver time-slice accounting on the send path, we split 1 broadcast into N separate events and enqueue each individually.

I concur with @hidenori-shinohara here: probably this is a residual message from the era where each peer's "work" was always implicitly serialized behind its read-completions, and so as long as read-completions had `shouldAbort` checks on them, entering `CLOSING` state before a read-completion fired meant no more `sendMessage`s could be generated from the work-on-a-peer done by that read-completion (broadcasts from other peers wouldn't find it because `CLOSING` also synchronously removes the peer from the peer lists).

This assumption hasn't been true for a while now, and I'm not sure it's really bad to violate it. At worst it means someone enqueued some logical no-ops they might want to have avoided enqueueing. But it's also possible (even likely) that those weren't no-ops when they were enqueued -- that the peer entered `CLOSING` state _after_ the work was enqueued. That's just an artifact of us doing more time slicing than we did before, it could even happen if we were enqueueing on the ASIO queue rather than the `Scheduler`. 

The only solutions I can think of are:

  - put a `shouldAbort` check on every lambda that gets queued (anywhere) to check again, before it does anything, whether the peer it was originally associated with has entered `CLOSING` state and therefore it should self-inhibit.
  - add a non-error-emitting `shouldAbort` check at the start of `sendMessage`, in place of the existing error, and accept that possibly-bogus work gets done, generates a message to send, and then drops it.
  - add an optional associated peer to events in the `Scheduler` -- perhaps a weak pointer -- such that the `Scheduler` checks _every_ event systematically to see if it's executing on behalf of a peer that's `CLOSING` and if so drops it before it runs.

(Or any combination thereof -- it's harmless to check `shouldAbort` both before and after doing work, and the call graph isn't so obvious that you can tell that a given set of callers covers all paths that arrive at `sendMessage`.)

**Comment by hidenori-shinohara** [comment] 2021-08-03 19:38
To add to what @graydon mentioned...

I checked many of the callers of `sendMessage()` such as `sendHello`, `sendAuth`, .... Many of them are indeed (directly or indirectly) called by a function that checks the state in some way. Checking `shouldAbort()` is fairly common like in `Peer::recvRawMessage`, but we do this in many forms such as checking `mState >= GOT_HELLO` in `Peer::recvHello`, or simply setting `mState = CONNECTED` before calling `sendHello()` in `Peer::connectHandler`.

Another interesting example I found: `HerderImpl::getMoreSCPState()` calls `sendGetScpState` which in turn calls `sendMessage`. But this is done on the list returned by `mApp.getOverlayManager().getRandomAuthenticatedPeers()`, so any `Peer`s with `mState = CLOSING` will not be iterated.

As this analysis of going through all the function calls inevitably gets fairly complicated, 
 I wouldn't say I'm certain, but I'm relatively confident that I was able to verify most of the instances, except for `sendErrorAndDrop`. 

`sendErrorAndDrop` is called at 18 different places, inside `CommandHandler.cpp`, `TCPPeer.cpp`, `Peer.cpp`, `OverlayManagerImpl.cpp`, and `SurveyManager.cpp`, and the number of places to check seems huge since they in turn are called at multiple places. I tried to verify as many as I can, but it just gets so complicated to the point that I wasn't sure if I could do this manually while being confident about not missing cases.

**Closed** 2021-08-07 00:20 UTC
Labels: bug
