### ISSUE TITLE
Accounts cannot be created and merged in the same transaction

### ISSUE THREAD

**Issue by pselden** [stellar/stellar-core#1829] opened 2018-11-10 07:37 UTC
# Issue type
bug

# Version found
v10.0.0

# Issue description
Accounts cannot be created and merged in the same transaction. I was trying to use an uninitialized account as the source for a transaction and then delete it in the same transaction (useful for requiring a signature from an uninitialized account or possibly some sort of mixing service), but it no longer works as of version 10.

This is because this line here https://github.com/stellar/stellar-core/blob/4dab9625d42b252d3f11500151ffcc66a1cd5ad2/src/transactions/MergeOpFrame.cpp#L103 prevents the sequence number from being used in the same ledger it was created (due to the = part of >=).

## Actual result
The merge operation failed with ACCOUNT_MERGE_SEQNUM_TOO_FAR

## Expected result
The create and merge should have succeeded.

## Supporting Files
Here's a sample that creates an account and then merges it in the same transaction: https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=create&values=eyJ0eCI6IkFBQUFBTUo3THFqY0c4VHQ3aGdnakVUbE4wdGVWS0tyUExvMEUycW5ueVc2MzBWNUFBQUJMQUFKWjVrQUFBQUNBQUFBQUFBQUFBQUFBQUFEQUFBQUFBQUFBQUVBQUFBQUdaeDA4VnJrV1FZTEFTUlVyZkViWmpvNVg4Q1NKclh3WUVtS0FEcVVGOTRBQUFBQUFBQUFBQUNZbG9BQUFBQUFBQUFBQUFBQUFBRExuWGkwVTlOZFMycWRHTWp1YWNKaE5VZkdpQWFKS0pmWGF2WDRIS1hFQUFBQUFBQUFtSmFBQUFBQUFRQUFBQURMblhpMFU5TmRTMnFkR01qdWFjSmhOVWZHaUFhSktKZlhhdlg0SEtYRUFBQUFBQWdBQUFBQXduc3VxTndieE8zdUdDQ01ST1UzUzE1VW9xczh1alFUYXFlZkpicmZSWGtBQUFBQUFBQUFBaHlseEFBQUFBQkFidC9TYUNvenE4MFVZU3lobzg5ekVOa25qb0pNTjdaVWhYLzFFRWNWMTBKeTBYRkZpYitUN1FUREwrdm1CVGt3eS9SbFU3bkFnS1JxUGQ1c2N0S0RBcnJmUlhrQUFBQkF1K3hTWHVBbEhYL1BIcXlLa0pPQWhsZnFRSmw1OThLTzdDUXZBR1poSXlkVXFCRHZ1S2tRbmlUSnY4eW1LVS9lemlock1UK1FsT2RqV0IxdkRyaytCQT09In0%3D&network=test

**Comment by MonsieurNicolas** [comment] 2018-11-12 22:32
This is by design (we have a [test case for this](https://github.com/stellar/stellar-core/blob/073cb708909d9a37130f390368da4d003a3ce3b2/src/transactions/MergeTests.cpp#L120)).

In a nutshell, the reason for this is when looking at it from the other order: if a transaction deletes an account, we want to reduce the chances that the account gets recreated (potentially by somebody else, this is a feature of create account) and pre-signed transactions that were targeting the account before the merge would be playable by the network as if the merge never happened.

There is a [discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/stellar-dev/EHMVkvHdCI8) on the protocol repo for deterministic accounts which probably would not have this limitation for the particular use case.

**Comment by MonsieurNicolas** [comment] 2018-12-06 22:18
closing as this would be a protocol change (that need to be discussed in the protocol repo)

**Closed by MonsieurNicolas** 2018-12-06 22:18 UTC
