### ISSUE TITLE
Logging information randomly stops being written to stdout

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#802] opened 2015-09-28 21:14 UTC
This was a weird one.  I had a running stellar-core node (isolated, local only) in a terminal that all of a sudden stopped logging to stdout.  Here's the last few lines from the terminal:

```
2015-09-28T13:47:31.978 a68f1d [] [Process] DEBUG process 32112 exited 0: gzip -c tmp/snapshot-278ac2db301c5a43/results-000001bf.xdr
2015-09-28T13:47:31.978 a68f1d [] [Process] DEBUG process 32092 exited 0: gzip -c tmp/snapshot-278ac2db301c5a43/ledger-000001bf.xdr
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Setting results-000001bf.xdr to state 4
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Setting results-000001bf.xdr to state 5
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Making remote directory results/00/00/01
2015-09-28T13:47:31.978 a68f1d [] [Process] DEBUG Running: mkdir -p /tmp/stellar-core/history/vs/results/00/00/01
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Some file-puts still in progress
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Setting ledger-000001bf.xdr to state 4
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Setting ledger-000001bf.xdr to state 5
2015-09-28T13:47:31.978 a68f1d [] [History] DEBUG Making remote directory ledger/00/00/01
2015-09-28T13
```

Notice, it ends in the middle of a timestamp.  Other than stdout not being written to, the other things that I checked appeared to be working fine:  ledgers were closing and being written to sql, the `/info` command and others were working.

**Comment by nullstyle** [comment] 2015-09-28 21:15
It appears to be related to a history push.  Here's a another snippet:

```
2015-09-28T14:15:05.689 a68f1d [] [History] DEBUG Making remote directory transactions/00/00/02
2015-09-28T14:15:05.689 a68f1d [] [Process] DEBUG Running: mkdir -p /tmp/stellar-core/history/vs/transactions/00/00/02
2015-09-28T14:15:05.690 a68f1d [] [History] DEBUG Some file-puts still in progress
2015-09-28T14:15:05.690 a68f1d [] [Process] DEBUG process 34399 exited 0: mkdir -p /tmp/stellar-core/history/vs/ledger/00/00/02
2015-09-28T14:15:05.690 a68f1d [] [Process] DEBUG process 34391 exited 0: mkdir -p /tmp/stellar-core/history/vs/results/00/00/02
2015-09-28T14:15:05.690 a68f1d [] [History] DEBUG Setting ledger-000002ff.xdr to state 6
2015-09-28T14:15:05.690 a68f1d [] [History] DEBUG Setting ledger-000002ff.xdr to state 7
2015-09-28T14:15:05.690 a68f1d [] [History] INFO  Publishing ledger-000002ff.xdr
2015-09-28T14:15:05.690 a68f1d [] [Process] DEBUG Running: cp tmp/snapshot-97d5ee6f4c925972/ledger-000002ff.xdr.gz /tmp/stellar-core/history/vs/ledger/00/00/02/ledger-000002ff.xdr.gz
2015-09-28T14:15:05.691 a68f1d [] [History] DEBUG Some file-puts still in progress
2015-09-28T14:15:05.691 a68f1d [] [History] DEBUG Setting results-000002ff.xdr to state 6
2015-09-28T14:15:05.691 a68f1d [] [History] DEBUG Setting results-000002ff.xdr to state 7
2015-09-28T14:15:05.691 a68f1d [] [History] INFO  Pub
```

**Comment by nullstyle** [comment] 2015-09-28 21:31
My config:

```
# simple configuration for a standalone test "network"
# see stellar-core_example.cfg for a description of the configuration parameters

HTTP_PORT=8080
PUBLIC_HTTP_PORT=false
RUN_STANDALONE=true

NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

NODE_SEED="SDQVDISRYN2JXBS7ICL7QJAEKB3HWBJFP2QECXG7GZICAHBK4UNJCWK2"
NODE_IS_VALIDATOR=true

#DATABASE="postgresql://dbname=stellar user=postgres password=password host=localhost"
DATABASE="postgresql://dbname=hayashi_development host=localhost port=5432"

COMMANDS=["ll?level=debug"]

FAILURE_SAFETY=0
UNSAFE_QUORUM=true
#The public keys of the Stellar testnet servers
[QUORUM_SET]
THRESHOLD_PERCENT=100
VALIDATORS=[
"GCTI6HMWRH2QGMFKWVU5M5ZSOTKL7P7JAHZDMJJBKDHGWTEC4CJ7O3DU"]

[HISTORY.vs]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"
```

**Comment by graydon** [comment] 2015-09-29 06:46
Yeah this is probably a bug in the process spawning code. either misusing posix_spawn or failing to interact with the asio loop properly or both. I'll look at it tomorrow unless something else is higher priority.

**Comment by graydon** [comment] 2015-09-30 21:06
Hm. I've tried reproducing this for a while today and am not able to. Can you tell me a little more about your system setup? OS version, build compiler, postgres version, anything peculiar about the version you were running, etc.? Was this just a plain checkout and build?

**Comment by nullstyle** [comment] 2015-09-30 23:32
I wasn't able to repro with a fresh build on my home laptop :

Machine:  Macbook Pro Retina (mid 2012) w/ SSD
OS:  OS X Yosemite 10.10.4
clang: Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
postgres: 9.4.4

I'll get you the appropriate information from my work laptop tomorrow.

**Comment by nullstyle** [comment] 2015-10-02 17:02
I'm no longer able to replicate this error on my work laptop, either.  Sorry for the wasted time, graydon.

**Comment by MonsieurNicolas** [comment] 2015-10-27 00:23
It seems we just run into this on linux while catching up (testnet 002)
```
2015-10-26T19:04:30.694 a824cd [History DEBUG] Replaying ledger 132714
2015-10-26T19:04:30.694 a824cd [History DEBUG] Ledger 132714 has 0 transactions
2015-10-26T19:0
```

**Comment by MonsieurNicolas** [comment] 2015-10-27 00:24
could also be that CLOG is not thread safe

**Comment by bartekn** [comment] 2016-11-22 16:53
I've experienced it several times too.

**Comment by vogel** [comment] 2016-11-28 13:40
I've never experienced that one. I'll try to find out the reason.

**Comment by vogel** [comment] 2017-01-05 17:26
Only on MacOSX

**Comment by vogel** [comment] 2017-01-13 14:35
After 3 days on MacOSX output is still visible.

**Comment by bartekn** [comment] 2017-01-13 14:39
It's really hard to repro. I've been running stellar-core for at least a year and it happened only 2-3 times.

**Comment by bartekn** [comment] 2017-04-10 15:23
OK, more info on this one. I built c7a7f76ef806def318cd25f8a911d0f409aeb4af and try to catchup complete.

First attempt:
```
2017-04-10T16:59:17.721 GCL53 [History INFO ] Catching up: downloading ledger files 42493/157533 (26%)
2017-04-10T16:59:17.721 GCL53 [History INFO ] Catching up: downloading ledger files 42494/157533 (26%)
2017-04-10T16:59:17.772 GCL53 [History INFO ] Catching up: downloading ledger files 42495/157533 (26%)
2017-04-10T16:59:17.772 GCL53 [History INFO ] Catching up: downloading ledger files 42496/157533 (26%)
2017-04-10T16:59:17.772 GCL53 [History INFO ] Catching up: downloading ledger files 4249
```
Second attempt:
```
2017-04-10T17:03:35.315 GCGAO [History INFO ] Catching up: downloading ledger files 4603/157538 (2%)
2017-04-10T17:03:35.468 GCGAO [History INFO ] Catching up: downloading ledger files 4604/157538 (2%)
2017-04-10T17:03:35.473 GCGAO [History INFO ] Catching up: downloading ledger files 4605/157538 (2%)
2017-04-10T17:03:35.473 GCGAO [History INFO ] Catching up: downloading ledger files 4606/157538 (2%)
2017
```
Third attempt:
```
2017-04-10T17:23:02.279 GCKCN [History INFO ] Catching up: downloading ledger files 10088/157542 (6%)
2017-04-10T17:23:02.296 GCKCN [History INFO ] Catching up: downloading ledger files 10089/157542 (6%)
2017-04-10T17:23:02.316 GCKCN [History INFO ] Catching up: downloading ledger files 10090/157542
```

Looks like I can repro this each time now. Anything I can do to try it down?

**Comment by jedmccaleb** [comment] 2017-04-10 16:05
you are on mac?

**Comment by bartekn** [comment] 2017-04-10 16:06
Yes, mac os sierra.

**Comment by MonsieurNicolas** [comment] 2017-10-03 17:45
Do you have actual repro steps for this that one can follow? If so, can you paste here? @bartekn

**Comment by bartekn** [comment] 2017-10-03 18:20
No, it's quite random. But we were talking about this with @zbyszkol few weeks ago while he was working on logger and he thinks it's because logger is not thread safe.

**Comment by MonsieurNicolas** [comment] 2017-10-03 18:38
It looks like there were updates on the thread-safety front in the logging library that we use. It's not in a release yet but available in current master. We'll have to do some more tests.

**Comment by MonsieurNicolas** [comment] 2018-03-28 23:34
Something that we could do: we're not calling `notify_fork` before and after forking http://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/io_service/notify_fork.html

I imagine that we don't really need to do anything in the child as we want to just "exec" but it may cause asio to properly stop doing work while the two processes figure things out. 

note that the contract for `notify_fork` is a bit strange as it's not thread safe, which could be problematic when launching processes from worker threads

**Comment by bartekn** [comment] 2019-02-07 18:32
Just experienced this in `v10.2.0rc2`:
```
2019-02-07T19:30:38.257 GCF6V [History INFO] Catching up: downloading ledger files 117/272 (43%)
2019-02-07T19:30:38.258 GCF6V [History INFO] Catching up: downloading ledger files 118/272 (43%)
2019-02-07T19:30:38.258 GCF6V [History INFO] Catching up: downloading ledger files 119/272 (43%)
2019-02-07T19:30:38.259 GCF6V [History INFO] Catching up: downloading ledger files 120/272 (44%)
2019-02-07T19:30

```

**Comment by MonsieurNicolas** [comment] 2019-02-08 01:17
on MacOS, right @bartekn ?

**Comment by bartekn** [comment] 2019-02-08 12:30
Yes.

**Comment by MonsieurNicolas** [comment] 2021-02-23 23:19
closing for now: as we changed logging infra I expect this to not be a problem anymore

**Closed by MonsieurNicolas** 2021-02-23 23:19 UTC
Labels: bug
