### ISSUE TITLE
catch up: std::runtime_error: rmdir failed

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#986] opened 2016-01-23 12:32 UTC
In prod, during the catch up state, `stellar-core` terminates wit the exception `std::runtime_error:rmdir failed`
Any ideas ?
```
2016-01-22T23:24:44.561 GD4JS [Process WARN ] process 87491 exited 22: curl -sf http://history.stellar.org/prd/core-live/core_live_003/ledger/00/01/57/ledger-000157bf.xdr.gz -o tmp-prod/catchup-complete-001e6c4b-fa14429c463d34e6/ledger-000157bf.xdr.gz
2016-01-22T23:24:44.561 GD4JS [Process WARN ] process 87476 exited 22: curl -sf http://history.stellar.org/prd/core-live/core_live_003/ledger/00/01/56/ledger-000156ff.xdr.gz -o tmp-prod/catchup-complete-001e6c4b-fa14429c463d34e6/ledger-000156ff.xdr.gz
2016-01-22T23:24:44.561 GD4JS [Process WARN ] process 87456 exited 22: curl -sf http://history.stellar.org/prd/core-live/core_live_003/ledger/00/01/50/ledger-000150bf.xdr.gz -o tmp-prod/catchup-complete-001e6c4b-fa14429c463d34e6/ledger-000150bf.xdr.gz
2016-01-22T23:24:44.561 GD4JS [Process DEBUG] process 87436 exited 0: curl -sf http://history.stellar.org/prd/core-live/core_live_002/ledger/00/01/32/ledger-0001323f.xdr.gz -o tmp-prod/catchup-complete-001e6c4b-fa14429c463d34e6/ledger-0001323f.xdr.gz
2016-01-22T23:24:44.561 GD4JS [Work DEBUG] completed get-remote-file ledger/00/01/57/ledger-000157bf.xdr.gz
2016-01-22T23:24:44.562 GD4JS [Work DEBUG] work get-remote-file ledger/00/01/57/ledger-000157bf.xdr.gz : WORK_RUNNING -> WORK_FAILURE_RETRY
2016-01-22T23:24:44.562 GD4JS [Work WARN ] Scheduling retry #1/5 in 1 sec, for get-remote-file ledger/00/01/57/ledger-000157bf.xdr.gz
2016-01-22T23:24:44.562 GD4JS [Work DEBUG] completed get-remote-file ledger/00/01/56/ledger-000156ff.xdr.gz
2016-01-22T23:24:44.562 GD4JS [Work DEBUG] work get-remote-file ledger/00/01/56/ledger-000156ff.xdr.gz : WORK_RUNNING -> WORK_FAILURE_RETRY
2016-01-22T23:24:44.562 GD4JS [Work WARN ] Scheduling retry #1/5 in 1 sec, for get-remote-file ledger/00/01/56/ledger-000156ff.xdr.gz
20libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: rmdir failed
```

Some ledger file seems to be missing:
```
$ curl http://history.stellar.org/prd/core-live/core_live_003/ledger/00/01/57/ledger-000157bf.xdr.gz
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: prd/core-live/core_live_003/ledger/00/01/57/ledger-000157bf.xdr.gz</li>
<li>RequestId: 2B93DDD3ECA0E6F6</li>
<li>HostId: AaUsZEz5q9lyC6NwnNsQnmsGAY5zLY40n+N4bgZNRllhGWF6eZmf3pk587NmWdveajYPD0TC4Ho=</li>
</ul>
<hr/>
</body>
</html>
```

**Comment by graydon** [comment] 2016-02-17 22:24
003 had missing files in its early parts due to being brought into production after the network was live. I've repaired it now using [stellar-archivist](http://github.com/stellar/archivist) and confirmed that it can serve a catchup-complete, so I'm closing this. Let me know if you see it again.

**Closed by graydon** 2016-02-17 22:24 UTC
