### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by SalleryWang** [stellar/stellar-core#2268] opened 2019-09-09 06:45 UTC
centos 7
stellar-core  v11.2.0
Unable to resolve peer 'validator1.stellar.stronghold.co': Could not resolve 'validator1.stellar.stronghold.co': Host not found (authoritative) [OverlayManagerImpl.cpp:404]

**Comment by MonsieurNicolas** [comment] 2019-09-09 15:53
closing: not a bug

if you have a question, we would recommend that
you:

* Take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation
  related to Stellar.
* If you can't find an answer to your question, please submit a question to [Stellar's Stack
  Exchange][2].
* If your question is non-developer centric, take a look at [Stellar's Community][3].

In general, we close any issues that are questions best served elsewhere — we have a small
community of people that manages issues, and we want to ensure that the issues that remain open are
high quality (so we actually get around to implementing them!)

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community

**Closed by MonsieurNicolas** 2019-09-09 15:53 UTC
Labels: bug
