### ISSUE TITLE
Config upgrade validation

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#3749] opened 2023-05-22 21:03 UTC
Most (if not all) of the configuration entrees for the fees/limits have been implemented, but the upgrade validation hasn't been implemented for all of them yet.

**Comment by anupsdf** [comment] 2023-07-03 21:28
Closing as duplicate of https://github.com/stellar/stellar-core/issues/3802

**Closed by anupsdf** 2023-07-03 21:28 UTC
