### ISSUE TITLE
Node unexpectedly quit, possibly with "Exception in processEnvelope state"

### ISSUE THREAD

**Issue by sscondie** [stellar/stellar-core#1041] opened 2016-06-15 14:54 UTC
My stellar-core node quit sometime last night.  The last statement printed to the logs was the following:

```
2016-06-15T06:23:19.429 GDI2V [SCP ERROR] Exception in processEnvelope state: {
   "slots" : {
      "4872416" : {
         "ballotProtocol" : {
            "ballot" : "(<null_ballot>)",
            "heard" : true,
            "phase" : "PREPARE",
            "state" : "i: 4872416 | PREPARE | b: (<null_ballot>) | p: (<null_ballo
t>) | p': (<null_ballot>) | h: (<null_ballot>) | c: (<null_ballot>) | M: 0"
         },
         "nomination" : {
            "roundnumber" : 0,
            "started" : false
         },
         "quorum_sets" : null,
         "validated" : false
      }
   }
}
 processing envelope: {ENV@sdf_watcher2 |  i: 4872416 | EXTERNALIZE | c: (1,[  txH
: 3f2336, ct: 1465971798, upgrades: [ ] ]) | h.n: 1 | (lastD): d60582 } [Slot.cpp:
137]
```

I'm on version v0.5.0-20-gd5dfd5b

**Comment by vogel** [comment] 2016-09-15 15:43
Currently I don't have enough information to fix this - this error occurs very rarery and is hard to reproduce. Improved error messages for "failed to open XDR file" were added that should help identify cause of this bug when it appears again.

**Comment by vogel** [comment] 2016-09-28 11:19
Got exception with new debug info:
2016-09-28T10:49:24.908 <test> [Fs FATAL] failed to open XDR file: stellar-core-test-4a5414293b3164bd/tmp/bucket-503aa1491253bebc/tmp-bucket-7f61e386195fdb13.xdr, reason: 117 [XDRStream.h:111]

Reason 117 is defined as EUCLEAN. Needs investigation.

**Comment by vogel** [comment] 2017-03-06 10:47
Still happens from time to time with more reasonable error core 2.

**Comment by mvaneijk** [comment] 2017-03-06 11:20
My node quit 2 days ago, nothing in the info log. I put on trace logging, if it happens again, I will post here.

**Comment by MonsieurNicolas** [comment] 2017-10-10 18:44
@mvaneijk did you ever run into this again?

**Comment by MonsieurNicolas** [comment] 2017-11-28 21:29
Doing some googling around seems to indicate that this error is triggered when there is some sort of filesystem corruption (typically xfs but may happen on ext4 as well); I'd recommend rebuilding whatever partition this happened on as it seems to be the only good way to get rid of it.
Regardless, I am closing this issue as it doesn't seem to be a stellar-core problem.

**Closed by MonsieurNicolas** 2017-11-28 21:29 UTC
