### ISSUE TITLE
stuck on bucket-repair

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#931] opened 2015-11-21 18:10 UTC
```
2015-11-21T18:00:46.863 GBGR2 [default INFO ] {   "info" : {
     "build" : "v0.3.1-2-g4e632f5",
     "extra" : "Catchup mode 'bucket-repair'",
     "ledger" : {
        "age" : 97316,         "closeTime" : 1448031530,
        "hash" : "28eb27697aaba523d4b873c6d2487c898117e71a950778492c0b2ae4687da35f",
        "num" : 914185
     },
     "network" : "Public Global Stellar Network ; September 2015",      "numPeers" : 8,
     "protocol_version" : 1,
     "state" : "Joining SCP"
  }
}


2015-11-21T17:23:29.453 GBGR2 [default INFO ] Starting stellar-core v0.3.1-2-g4e632f5
2015-11-21T17:23:29.454 GBGR2 [default INFO ] Config from stellar-core.cfg
2015-11-21T17:23:29.456 GBGR2 [Database INFO ] Connecting to: sqlite3://stellar.db
2015-11-21T17:23:29.462 GBGR2 [SCP INFO ] LocalNode::LocalNode@GBGR2 qSet: 35f484
2015-11-21T17:23:29.462 GBGR2 [default INFO ] Listening on 127.0.0.1:11626 for HTTP requests
2015-11-21T17:23:29.463 GBGR2 [History INFO ] Archive 'sdf1' has 'get' command only, will not be written
2015-11-21T17:23:29.464 GBGR2 [History INFO ] Archive 'sdf2' has 'get' command only, will not be written
2015-11-21T17:23:29.464 GBGR2 [History WARN ] No writable archives configured, history will not be written.
2015-11-21T17:23:29.465 GBGR2 [default INFO ] Loading last known ledger
2015-11-21T17:23:29.468 GBGR2 [Ledger WARN ] Some buckets are missing in 'buckets'.
2015-11-21T17:23:29.469 GBGR2 [Ledger WARN ] Attempting to recover from the history store.
2015-11-21T17:23:29.470 GBGR2 [History INFO ] Catchup BEGIN, initLedger=0, guessed nextLedger=64, anchor checkpoint=63
2015-11-21T17:23:29.958 GBGR2 [History INFO ] Catchup mode 'bucket-repair'
2015-11-21T17:23:29.959 GBGR2 [Ledger INFO ] Loaded last known ledger: [seq=914184, hash=28eb27]
```
Then nothing other than from overlay for the next 30 min

**Comment by graydon** [comment] 2015-11-23 17:02
Huh. Don't suppose you have a copy of the data container and/or full debug log? It's presumably ilooping ... somewhere. First guess is it wants a bucket that never got published (eg. a temporary being used in a merge). But it's hard to tell from that.

**Comment by jedmccaleb** [comment] 2015-11-23 17:09
I think it happened to him after a segfault so things could have been left in a weird state. It happened after a segfault for someone else for sure.

**Comment by graydon** [comment] 2015-11-23 17:13
yeah. there's not much we can do in that case except notice a bucket is unretrievable and shut down. or at least issue more obvious messages about ilooping.

**Comment by jedmccaleb** [comment] 2015-11-23 17:30
Yeah at the very least it should tell the user they are stuck.  But also can't it just fetch new buckets from the history archive?

**Comment by graydon** [comment] 2015-11-23 17:49
Only if they were published. It has a local state it is trying to recreate, including a random set of buckets that might include some that didn't get published.

Possibly it should switch to catchup mode when it can't recreate the local state. I didn't write this mode, it's guillaume's stuff. I'll be rewriting it in the process of redoing the history-system implementation.

**Comment by jedmccaleb** [comment] 2015-11-23 17:52
ok sounds good. I'll just close this since it will change once your rewrite is done

**Comment by graydon** [comment] 2015-11-23 17:54
Eh, I'm going to leave it open to remind me to handle this case, or at least think it through and make sure we're doing the best we can.

**Comment by jedmccaleb** [comment] 2016-01-18 22:51
Is this safe to close now?

**Comment by graydon** [comment] 2016-01-20 19:46
I guess. It doesn't switch to catchup mode automatically, but since we directly inspect the publish queue during bucket-deletion now (as of e928467c56a203ae20864d7ec901e0291c787d1f) this shouldn't happen nearly as often. Also it'll time out during startup / repair attempts. I'll add a change that hard-fails when that happens, to ensure the user gets a real error.

As far as "fixing" such a situation, should it re-occur, I'm not really sure there are other viable options. We can't tell how the state we have in the DB differs from the buckets we have, so I don't really think there's a viable way to initiate a catchup. I can't think of anything that'll work aside from hard-failing and telling the user to reset their local state.

But as I say, I _think_ this should occur far less often with the fixes above to bucket deletion. Time will tell. I'll post the one addition mentioned and we'll see if this reoccurs a lot. If so reopen.

**Comment by graydon** [comment] 2016-01-22 19:08
Update: I spent yesterday afternoon and some of this morning trying to find or reproduce a potential bucket-loss situation during the snapshot-and-commit path of the ledger manager, and I couldn't produce anything. I'll keep the branch around but for now I think I'm hitting diminishing returns. Going to close this bug for now. If you see this happen again, reopen and we can try to diagnose which bucket got lost and where.

**Closed by graydon** 2016-01-22 19:08 UTC
Labels: bug
