### ISSUE TITLE
TMP_DIR_PATH & BUCKETS_DIR_PATH must be on same volume

### ISSUE THREAD

**Issue by matschaffer** [stellar/stellar-core#367] opened 2015-03-31 08:29 UTC
Otherwise you hit something like this:

```
31/03/15 08:25:20 [Bucket] DEBUG Adopting bucket file tmp/bucket-a7cd8d6348e09b0f/tmp-bucket-0cbad2b3bd846728.xdr as /data/stellar-core/buckets/bucket-81bc70b3ecdeb5a633995d6b394174879e97fc38bf4c3d2b58a760b6fa823769.xdr
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to rename bucket
Aborted (core dumped)
```

Probably something we can address with documentation for now though having the process call out the problem specifically could be handy.

**Comment by nullstyle** [comment] 2015-04-23 16:41
For some further notes, I accidentally cleared my `/tmp` dir (not a big deal, just reboot and everything is fine) by setting `TMP_DIR_PATH` to `/tmp`

My intuition from other applications is that when you set `TMP_DIR_PATH` or equivalent, you're not actually giving sole ownership of that dir to the application, but rather telling the application what base directory to use when creating a directory that it has ownership over.  It was not expected that it cleared `/tmp`

**Comment by MonsieurNicolas** [comment] 2015-09-04 00:47
Can we move this issue to later? I see that it's assigned to you @graydon ; maybe you were already working on it?

**Comment by vogel** [comment] 2016-09-22 17:20
What about new option replacing these two?
DATA_DIR_PATH, then current TMP_DIR_PATH = DATA_DIR_PATH/tmp and BUCKETS_DIR_PATH = DATA_DIR_PATH/tmp

We could assume:
DATA_DIR_PATH = setting from config, if present
DATA_DIR_PATH = BUCKETS_DIR_PATH/.. if BUCKETS_DIR_PATH present
DATA_DIR_PATH = . otherwise

**Comment by jedmccaleb** [comment] 2016-09-23 02:56
Why do we need two? cant we just have BUCKETS_DIR_PATH and then TMP_DIR_PATH goes away and we use BUCKETS_DIR_PATH/tmp for what would have been TMP_DIR_PATH

**Comment by vogel** [comment] 2016-09-23 06:46
Yes, that is another option. The only problem is (but not at all important) that in that case we would store some history data, so it does not match being under BUCKETS_DIR_PATH. But otherwise it is also a good solution (and with less compatibility issues that what I've presented).

So I'll go with that one.

**Comment by vogel** [comment] 2016-10-04 12:03
It seem that PR failure is some random bug in tests, not caused by this PR.
For reference, different instances of the same issue:

https://travis-ci.org/stellar/stellar-core/jobs/144290661
https://travis-ci.org/stellar/stellar-core/jobs/111916250

I think it requires separate investigation

**Closed** 2016-10-12 09:11 UTC
Labels: enhancement, in progress
