### ISSUE TITLE
Run in-memory / start-from

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2486] opened 2020-03-30 17:28 UTC
As part of the work on captive stellar-cores for faster horizon ingestion (eg. https://github.com/stellar/go/pull/2322), `stellar-core run` command might need to be modified to operate in-memory only.

If so, it will also need a new flag indicating which ledger to "start from" -- passed from horizon indicating horizon's last-ingested ledger -- meaning "do an offline catchup _to_ N, not emitting metadata, and then an online catchup _from_ N, emitting metadata during replay".

If however we're not storing ledger state in memory for _online_ captive cores, we can have horizon just run two commands when initiating a captive core: once to offline-catchup, and once to run.

**Comment by MonsieurNicolas** [comment] 2020-08-01 17:10
duplicate of #2634

**Closed by MonsieurNicolas** 2020-08-01 17:10 UTC
Labels: enhancement
