### ISSUE TITLE
Assertion failed in work/BasicWork.cpp (Version: v12.2.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2433] opened 2020-02-12 14:14 UTC
## Steps to Reproduce

I started stellar-core after 16 hours since stopping it. During ledger apply stage I pressed Control+C (SIGINT).

## Expected Result

Application exits gracefully.

## Actual Result

```
Assertion failed: (isDone() || mState == InternalState::PENDING), function ~BasicWork, file work/BasicWork.cpp, line 45.
```

### stellar-core Version
v12.2.0

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)

Darwin Stellars-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

* Are you running from the command line? From a container?

Terminal.

* Did you pass in special parameters when building the app?

No.

## Supporting Files

If you have any supporting files, please paste them or link to a relevant Github gist or archive link (such as an S3 bucket).

https://gist.github.com/bartekn/f88ffdc4bd3ebb69155de2fa00f7b46f

**Comment by MonsieurNicolas** [comment] 2020-02-12 15:15
Duplicate of #2395 that was fixed in 12.3.0

**Closed by MonsieurNicolas** 2020-02-12 15:15 UTC
Labels: bug
