### ISSUE TITLE
Stellar Core validator node (Version: stellar-core 21.3.1)

### ISSUE THREAD

**Issue by Nik-1989** [stellar/stellar-core#4457] opened 2024-09-05 08:01 UTC
Hello everyone. Is it normal that synchronization takes so long?

"startedOn" : "2024-09-04T15:26:44Z",
      "state" : "Catching up",
      "status" : [
         "Catching up to ledger 53344831: Download & apply checkpoints: num checkpoints left to apply:810227 (2% done)",
         "Publishing 23286 queued checkpoints [63-1490303]: update-archives-0000003f:getting archives"
      ]
   }
}
Please tell me, will this process take 2 weeks? Why so slowly? Powerful server with good ssd disks.

**Comment by marta-lokhova** [comment] 2024-09-05 20:57
Hello. It seems like you're trying to replay and publish full history since genesis, which is expected to take weeks (it's 9 years of history!)

If you'd like to setup a full history archive, you could clone an existing history archive using Stellar Archivist, then join the network without replaying full history. https://developers.stellar.org/docs/validators/admin-guide/publishing-history-archives#complete-history-archive has more info.

**Comment by marta-lokhova** [comment] 2024-09-06 16:53
Closing as this is not a bug

**Closed by marta-lokhova** 2024-09-06 16:53 UTC
Labels: bug
