### ISSUE TITLE
Ledger: processFeesSeqNums error @ 1 : Unexpected database state (Version: 17.1.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#3085] opened 2021-06-15 23:01 UTC
## Issue Description

Got this when running Captive-Core in Horizon:
```
ERRO[2021-06-16T00:55:39.351+02:00] Ledger: processFeesSeqNums error @ 1 : Unexpected database state  pid=79181 service=ingest subservice=stellar-core
ERRO[2021-06-16T00:55:39.351+02:00] Ledger: Please report this bug along with this log file if this was not expected  pid=79181 service=ingest subservice=stellar-core
ERRO[2021-06-16T00:55:39.351+02:00] History: Replay failed: Unexpected database state  pid=79181 service=ingest subservice=stellar-core
INFO[2021-06-16T00:55:39.352+02:00] Assertion failed: (isDone() || mState == InternalState::PENDING), function ~BasicWork, file work/BasicWork.cpp, line 47.  pid=79181 service=ingest subservice=stellar-core
ERRO[2021-06-16T00:55:39.352+02:00] History: Archive sdf_testnet_2 maybe contains corrupt file transactions/00/16/b7/transactions-0016b73f.xdr.gz  pid=79181 service=ingest subservice=stellar-core
```

## Steps to Reproduce

Not sure, I was restarting Horizon with Captive Core multiple times to reproduce #3083.

## Expected Result
No crash.

## Actual Result
Crash.

### stellar-core Version
17.1.0

### Environment
* Operation System & Version (You can usually obtain from `uname -a`) Mac OS
* Are you running from the command line? From a container? Command Line
* Did you pass in special parameters when building the app? Captive Core
* Please add any additional relevant configuration related to this bug report.

## Supporting Files

Horizon log:  https://gist.github.com/bartekn/1817d03753e6ad55079632f049a7a60f

**Comment by bartekn** [comment] 2021-06-15 23:09
It happens every time now. Possibly the DB got corrupted. Here it is: https://drive.google.com/drive/folders/1aqNq_8d8IF4Bf9HM7qjdbRW98OGh0TeT?usp=sharing

**Comment by marta-lokhova** [comment] 2021-06-15 23:16
How does Horizon stop captive core? It seems like the database may have been corrupted on shutdown (maybe Horizon doesn't wait until the process finishes?)

**Comment by marta-lokhova** [comment] 2021-06-15 23:27
Could you share the buckets at well if you have them?

**Comment by bartekn** [comment] 2021-06-15 23:28
> How does Horizon stop captive core? It seems like the database may have been corrupted on shutdown (maybe Horizon doesn't wait until the process finishes?)

Horizon should wait for the process to exit gracefully but I'm currently looking for bugs there.

> Could you share the buckets at well if you have them?

Just removed them :(.

**Comment by bartekn** [comment] 2021-06-15 23:31
OK, this is probably a bug in Horizon. Going to close this issue when I confirm it 100% tomorrow.

**Comment by marta-lokhova** [comment] 2021-06-15 23:35
yeah, please follow-up in this issue after your investigation

**Comment by marta-lokhova** [comment] 2021-06-16 01:37
@bartekn if you're able to reproduce this again, please share the buckets as well

**Comment by bartekn** [comment] 2021-06-16 11:38
Indeed Stellar-Core processed was killed by Horizon on exit (instead of sending SIGINT). This was working because there was not persistent storage before 17.1.0. I fixed it in https://github.com/stellar/go/pull/3694 (also removed `DISABLE_XDR_FSYNC` from `stellar-core.cfg`). I haven't been able to reproduce it since the code changes above so we can close it.

**Comment by bartekn** [comment] 2021-06-16 21:18
Added the log of the last execution before running into this issue yesterday: https://gist.github.com/bartekn/e0e3b9701485b19ae0c8ea356de02f7a I sent SIGINT to Horizon (by pressing Command+C) and it killed Stellar-Core by sending SIGKILL (it was before the fixes in https://github.com/stellar/go/pull/3694).

**Comment by bartekn** [comment] 2021-06-16 22:52
The one _before_ above: https://gist.github.com/bartekn/ac4ffbb661aaccbbb4db1b685cfbad95 it got killed by Horizon because of the unexpected ledger in the stream (persistency changed the first ledger streamed by Captive-Core - fixed in https://github.com/stellar/go/pull/3694).

**Comment by bartekn** [comment] 2021-06-23 19:07
I noticed another error when running Horizon with a fix (not using permanent directory):
```
default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate
```
I wonder if it's the same issue or should I open a new one?

**Comment by marta-lokhova** [comment] 2021-06-23 19:56
I suspect you ran into https://github.com/stellar/stellar-core/issues/3054 @bartekn, which got fixed in 17.2.0. To confirm, could you provide more context/logs?

**Comment by marta-lokhova** [comment] 2021-06-24 17:47
Indeed logs seem to confirm that this is due to https://github.com/stellar/stellar-core/issues/3054, as BucketManager tries to GC before the database is initialized. This should not be the case as of version 17.2.0, since we removed GC on destruction completely.

**Comment by MonsieurNicolas** [comment] 2021-07-12 21:24
I think this can be closed now, right @marta-lokhova ?

**Comment by marta-lokhova** [comment] 2021-07-12 21:57
yes, this is fixed by @graydon in https://github.com/stellar/stellar-core/pull/3093. Closing.

**Closed by marta-lokhova** 2021-07-12 21:57 UTC
Labels: bug
