### ISSUE TITLE
Offer exchange with indivisible assets

### ISSUE THREAD

**Issue by hard-codr** [stellar/stellar-core#1491] opened 2018-01-14 06:13 UTC
There is use-case I have, where it is not possible to sell assets in a fraction. Either asset goes as whole or none at all. ```stellar::OfferExchange``` crosses matching offer considering only best prices. So if I have a single unit of an asset to sell and there is the best offer which takes a fraction of that asset, it is executed first. And remaining asset it executed with next best offer. 

I checked the API and poked around in the code as well (specifically OfferExchange class), but didn't anything relevant to this use case. And from what I can gather, offer exchange is part of stellar-core, so there is nothing I do in the fringe application like horizon or my own application which will guarantee that assets will not be divided.

**Comment by MonsieurNicolas** [comment] 2018-01-15 23:39
discussions for protocol updates are done https://github.com/stellar/stellar-protocol/issues this one in particular seems to be a dupe of https://github.com/stellar/stellar-protocol/issues/23

**Closed by MonsieurNicolas** 2018-01-15 23:39 UTC
