### ISSUE TITLE
When catching up complete, ledger download will restart. 

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1031] opened 2016-05-12 17:05 UTC
```
2016-05-12T13:19:55.427 GAXP5 [History INFO ] Catching up: downloading ledger files 56966/64286 (88%)
2016-05-12T13:19:55.658 GAXP5 [Process WARN ] process 24329 exited 22: curl -sf http://s3-ap-northeast-1.amazonaws.com/confucius.tome.strllar.org/xlm/ledger/00/37/a0/ledger-0037a07f.xdr.gz -o /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-0037a07f.xdr.gz
2016-05-12T13:19:55.659 GAXP5 [Work WARN ] Scheduling retry #1/5 in 2 sec, for get-remote-file ledger/00/37/a0/ledger-0037a07f.xdr.gz
2016-05-12T13:19:55.736 GAXP5 [Work WARN ] Reached retry limit 5 for gunzip-file /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-0037807f.xdr.gz
2016-05-12T13:19:55.736 GAXP5 [Work WARN ] Reached retry limit 5 for batch-download-ledger-0000003f-003ec77f
2016-05-12T13:19:55.737 GAXP5 [Work WARN ] Scheduling retry #1/5 in 2 sec, for catchup-complete-003ec772
2016-05-12T13:19:56.081 GAXP5 [Process WARN ] process 24335 exited 22: curl -sf http://s3-ap-northeast-1.amazonaws.com/confucius.tome.strllar.org/xlm/ledger/00/37/a1/ledger-0037a13f.xdr.gz -o /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-0037a13f.xdr.gz
2016-05-12T13:19:56.081 GAXP5 [Work WARN ] Scheduling retry #1/5 in 2 sec, for get-remote-file ledger/00/37/a1/ledger-0037a13f.xdr.gz
2016-05-12T13:19:56.164 GAXP5 [History INFO ] Catching up: Retrying in 1 sec: catchup-complete-003ec772
2016-05-12T13:19:56.181 GAXP5 [Process WARN ] process 24337 exited 22: curl -sf http://history.stellar.org/prd/core-live/core_live_003/ledger/00/37/8b/ledger-00378bff.xdr.gz -o /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-00378bff.xdr.gz
2016-05-12T13:19:56.181 GAXP5 [Work WARN ] Reached retry limit 5 for get-remote-file ledger/00/37/8b/ledger-00378bff.xdr.gz
2016-05-12T13:19:56.181 GAXP5 [Work WARN ] Scheduling retry #1/5 in 1 sec, for gunzip-file /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-00378bff.xdr.gz
2016-05-12T13:19:56.857 GAXP5 [Process WARN ] process 24339 exited 22: curl -sf http://s3-ap-northeast-1.amazonaws.com/confucius.tome.strllar.org/xlm/ledger/00/37/9e/ledger-00379e3f.xdr.gz -o /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-00379e3f.xdr.gz
2016-05-12T13:19:56.857 GAXP5 [Work WARN ] Scheduling retry #3/5 in 7 sec, for get-remote-file ledger/00/37/9e/ledger-00379e3f.xdr.gz
2016-05-12T13:19:57.181 GAXP5 [Work WARN ] Scheduling retry #2/5 in 2 sec, for gunzip-file /home/stellar/tmp/catchup-complete-003ec772-4d062f526ca5906d/ledger-00378bff.xdr.gz
2016-05-12T13:19:59.033 GAXP5 [Work WARN ] Scheduling retry #1/5 in 36 sec, for get-history-archive-state
2016-05-12T13:19:59.040 GAXP5 [Herder INFO ] Quorum information for 4114828 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:19:59.046 GAXP5 [Ledger INFO ] Got consensus: [seq=4114830, prev=f1a780, tx_count=0, sv: [  txH: e8c7f4, ct: 1463048399, upgrades: [ ] ]]
2016-05-12T13:19:59.046 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 36 seconds)
2016-05-12T13:20:03.167 GAXP5 [Herder INFO ] Quorum information for 4114829 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:03.169 GAXP5 [Ledger INFO ] Got consensus: [seq=4114831, prev=24945b, tx_count=0, sv: [  txH: e88951, ct: 1463048404, upgrades: [ ] ]]
2016-05-12T13:20:03.169 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 32 seconds)
2016-05-12T13:20:08.059 GAXP5 [Herder INFO ] Quorum information for 4114830 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:08.061 GAXP5 [Ledger INFO ] Got consensus: [seq=4114832, prev=b461d7, tx_count=0, sv: [  txH: a50a3f, ct: 1463048409, upgrades: [ ] ]]
2016-05-12T13:20:08.061 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 27 seconds)
2016-05-12T13:20:13.169 GAXP5 [Herder INFO ] Quorum information for 4114831 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:13.172 GAXP5 [Ledger INFO ] Got consensus: [seq=4114833, prev=10dd9d, tx_count=0, sv: [  txH: f41e99, ct: 1463048411, upgrades: [ ] ]]
2016-05-12T13:20:13.172 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 22 seconds)
2016-05-12T13:20:17.996 GAXP5 [Herder INFO ] Quorum information for 4114832 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:17.999 GAXP5 [Ledger INFO ] Got consensus: [seq=4114834, prev=3b7b7a, tx_count=0, sv: [  txH: 7ffe8f, ct: 1463048412, upgrades: [ ] ]]
2016-05-12T13:20:17.999 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 18 seconds)
2016-05-12T13:20:19.095 GAXP5 [Herder INFO ] Quorum information for 4114833 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:19.097 GAXP5 [Ledger INFO ] Got consensus: [seq=4114835, prev=7c61a9, tx_count=0, sv: [  txH: dd3908, ct: 1463048416, upgrades: [ ] ]]
2016-05-12T13:20:19.097 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 16 seconds)
2016-05-12T13:20:24.168 GAXP5 [Herder INFO ] Quorum information for 4114834 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:24.170 GAXP5 [Ledger INFO ] Got consensus: [seq=4114836, prev=a95db5, tx_count=0, sv: [  txH: f8b19f, ct: 1463048421, upgrades: [ ] ]]
2016-05-12T13:20:24.170 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 11 seconds)
2016-05-12T13:20:28.102 GAXP5 [Herder INFO ] Quorum information for 4114835 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:28.105 GAXP5 [Ledger INFO ] Got consensus: [seq=4114837, prev=53d46f, tx_count=0, sv: [  txH: 5415b5, ct: 1463048429, upgrades: [ ] ]]
2016-05-12T13:20:28.105 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 7 seconds)
2016-05-12T13:20:32.203 GAXP5 [Herder INFO ] Quorum information for 4114836 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:32.206 GAXP5 [Ledger INFO ] Got consensus: [seq=4114838, prev=72ecf6, tx_count=0, sv: [  txH: 726443, ct: 1463048430, upgrades: [ ] ]]
2016-05-12T13:20:32.206 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 3 seconds)
2016-05-12T13:20:34.170 GAXP5 [Herder INFO ] Quorum information for 4114837 : {"agree":3,"disagree":0,"fail_at":1,"hash":"a150a6","missing":1,"phase":"EXTERNALIZE"}
2016-05-12T13:20:34.173 GAXP5 [Ledger INFO ] Got consensus: [seq=4114839, prev=57365a, tx_count=0, sv: [  txH: 93e621, ct: 1463048431, upgrades: [ ] ]]
2016-05-12T13:20:34.173 GAXP5 [History INFO ] Catching up: Awaiting checkpoint (ETA: 1 seconds)
2016-05-12T13:20:35.361 GAXP5 [History INFO ] Catchup COMPLETE downloading ledgers [63, 4114303]
2016-05-12T13:20:35.505 GAXP5 [History INFO ] Catching up: downloading ledger files 12/64286 (0%)
```
this is sad. Not sure if the fetching failed 5 retries which caused this but either way everything shouldn't be thrown away.

**Comment by tzdybal** [comment] 2016-06-15 21:24
This issue is caused by fetching failures. After 5 fails of single file download, the batch download work restarts. It is OK, because batch works checks if the file is already downloaded. 
Problem occurs after 5 fails of batch download work. The catchup work is restarted which results in recreation of the download dir - old directory and all downloaded files are removed (and new directory is created).

**Comment by vogel** [comment] 2016-10-24 15:51
Should be closed as PR was merged.

**Closed by vogel** 2016-10-24 15:51 UTC
