### ISSUE TITLE
Strange `NOTICE` lines emitted when creating tables for postgres database

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#172] opened 2015-02-24 19:43 UTC
Given a cleared postgres database, and starting stellard with `--new` you get something like the following log:

```
24/02/15 11:40:19 [default] INFO  Starting stellard-hayashi 2e46fd0-dirty
24/02/15 11:40:19 [default] INFO  Config from -
24/02/15 11:40:19 [default] INFO  Application constructing (worker threads: 8)
24/02/15 11:40:19 [default] INFO  Application constructed
24/02/15 11:40:19 [FBA] INFO  LocalNode::LocalNode@7eb7f3 qSet: 4f852d
24/02/15 11:40:19 [default] INFO  Listening on 127.0.0.1:39132 for HTTP requests
24/02/15 11:40:19 [default] INFO  Connecting to: postgresql://dbname=hayashi_test
NOTICE:  table "accounts" does not exist, skipping
NOTICE:  table "signers" does not exist, skipping
NOTICE:  table "accountdata" does not exist, skipping
NOTICE:  table "offers" does not exist, skipping
NOTICE:  table "trustlines" does not exist, skipping
NOTICE:  table "peers" does not exist, skipping
NOTICE:  table "storestate" does not exist, skipping
NOTICE:  table "ledgerheaders" does not exist, skipping
NOTICE:  table "txhistory" does not exist, skipping
24/02/15 11:40:19 [default] INFO  Creating the genesis ledger.
24/02/15 11:40:19 [CLF] INFO  Deleting bucket directory for new network: buckets
```

Please see the lines prefixed with `NOTICE:`.  It seems strange we are a) emitting log lines that don't follow our standard output format and b) don't really provide any context about what we're skipping.

**Comment by MonsieurNicolas** [comment] 2015-04-26 00:50
they don't follow our log format because they actually end up in stderr see #191 for more detail

**Comment by graydon** [comment] 2024-05-23 03:59
Dupe of #191 (and probably we will just delete postgres support before fixing this; but we don't need two bugs on it)

**Closed by graydon** 2024-05-23 03:59 UTC
