### ISSUE TITLE
crash in command line catchup

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1885] opened 2018-12-20 22:44 UTC
We're seeing intermittent crashes in acceptance tests.

Seen in d51f6222

Couple examples

```
/start: line 70:    16 Aborted                 (core dumped) stellar-core $CONFIG_OPTION --catchup-at $FROM --catchup-to $TO --output-file "${OUTPUT}"
parallel: This job failed:
./scripts/partial_catchup 23 24 1282879 testnet
```

```
/start: line 70:    18 Aborted                 (core dumped) stellar-core $CONFIG_OPTION --catchup-at $FROM --catchup-to $TO --output-file "${OUTPUT}"
parallel: This job failed:
./scripts/partial_catchup 19 24 1195327 testnet
```

**Comment by MonsieurNicolas** [comment] 2019-01-16 23:53
are you still looking at this @marta-lokhova ?

**Comment by marta-lokhova** [comment] 2019-01-17 01:47
@MonsieurNicolas I could not reproduce it locally, also it looks like there have been no failures since Dec 17. We could maybe switch log level to DEBUG and see if it fails again?

**Comment by marta-lokhova** [comment] 2019-01-17 22:31
Actually it happened again last night, seems like the same place every time.

**Comment by marta-lokhova** [comment] 2019-02-07 00:30
Update on this: we have not seen any crashes since #1929 was merged. My current theory is that the data race on `NtpClient::mCallbackCalled` caused `NtpWork` to be scheduled for completion twice (when `NtpWork` hits a timeout, and when `NtpClient` finishes on the background thread). This could cause strange things happen to the Work object. 

Closing this issue (will re-open if it comes back).

**Closed by marta-lokhova** 2019-02-07 00:30 UTC
